import type { TravelConfig } from '../types';

export const australiaTrip: TravelConfig = {
  slug: 'australia',
  countryName: 'Australia',
  theme: {
    ink: '#00008b',
    inkRgb: '0, 0, 139',
    cream: '#f4edcf',
    creamRgb: '244, 237, 207',
    paper: '#fffdf2',
    paperRgb: '255, 253, 242',
    accent: '#ffcd00',
    accentRgb: '255, 205, 0',
    secondary: '#00843d',
  },
  brand: {
    code: 'AU',
    year: '25',
  },
  home: {
    kicker: 'MAR—APR 2025',
    title: 'From Melbourne laneways to Sydney harbour.',
    description:
      'Eight autumn days across Melbourne and Sydney—coastal roads, native wildlife, city walks, and two arena concerts.',
    actionLabel: 'Open the Australia itinerary',
  },
  hero: {
    kicker: 'AUSTRALIA · AUTUMN 2025',
    title: ['Coastal roads,', 'harbour lights.'],
    intro:
      'An eight-day run from Melbourne’s gardens and Great Ocean Road to Sydney Harbour, with wildlife, railway steam, and two concerts along the way.',
    stamp: {
      number: '08',
      label: 'DAYS IN AUSTRALIA',
      dates: '30 MAR — 06 APR',
      ariaLabel: 'Trip dates March 30 to April 6, 2025',
    },
    facts: [
      { value: '02', label: 'city bases' },
      { value: '02', label: 'concert nights' },
      { value: '07', label: 'nights away' },
    ],
  },
  route: {
    kicker: 'THE AUSTRALIA ROUTE',
    title: 'Melbourne, the coast, then north to Sydney.',
    mapAriaLabel: 'Interactive map of the Australia itinerary',
    center: [-36.05, 147.1],
    zoom: 5,
    minZoom: 4,
    roads: [
      [
        [-37.8136, 144.9631],
        [-38.665, 143.1044],
        [-38.6471, 143.0699],
        [-38.759, 143.672],
        [-38.493, 144.887],
        [-37.8136, 144.9631],
      ],
      [
        [-37.8136, 144.9631],
        [-37.9104, 145.3534],
        [-38.332, 145.226],
        [-38.4835, 145.231],
        [-37.8136, 144.9631],
      ],
      [
        [-33.9399, 151.1753],
        [-33.8688, 151.2093],
        [-33.8472, 151.0649],
      ],
    ],
    flights: [
      [
        [-37.669, 144.841],
        [-33.9399, 151.1753],
      ],
    ],
  },
  itinerary: {
    kicker: 'DAY BY DAY',
    title: 'The Australia itinerary.',
    days: [
      {
        id: 'mar-30',
        date: 'MAR 30',
        day: 'SUNDAY',
        place: 'Beijing → Melbourne',
        weather: 'Cloudy',
        temperature: '15–21°',
        coordinate: [-37.8136, 144.9631],
        entries: [
          {
            type: 'flight',
            title: '01:05–15:35 · Beijing → Melbourne',
            detail: 'Beijing Capital T3 (PEK) → Melbourne T2 (MEL)',
            cost: 7684,
            costNote: 'International round-trip airfare · 2 people',
            costShared: true,
          },
          {
            type: 'drive',
            title: 'Uber',
            detail: 'Airport and city rides · combined trip total',
            cost: 1636,
            costShared: true,
          },
          {
            type: 'food',
            title: 'Infinite Wasabi',
            detail: 'Melbourne arrival meal',
            cost: 567,
          },
          {
            type: 'stay',
            title: 'Grand Hyatt Melbourne',
            detail: 'Free Night award',
            cost: 0,
            costNote: '1 night',
          },
        ],
      },
      {
        id: 'mar-31',
        date: 'MAR 31',
        day: 'MONDAY',
        place: 'Melbourne gardens',
        weather: 'Partly cloudy',
        temperature: '13–20°',
        coordinate: [-37.8304, 144.9796],
        entries: [
          {
            type: 'visit',
            title: 'Royal Botanic Gardens Victoria',
            detail: 'A quiet first full day in Melbourne',
          },
          { type: 'food', title: 'Humble Rays', cost: 649 },
          { type: 'food', title: 'TamJai Mixian', cost: 150 },
          {
            type: 'stay',
            title: 'Hyatt Centric Melbourne',
            cost: 2863,
            costNote: 'Night 1 of 3 · three-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'apr-1',
        date: 'APR 01',
        day: 'TUESDAY',
        place: 'The Great Ocean Road',
        weather: 'Partly cloudy',
        temperature: '13–20°',
        coordinate: [-38.665, 143.1044],
        entries: [
          {
            type: 'visit',
            title: 'Great Ocean Road day trip',
            detail: 'Twelve Apostles · Loch Ard Gorge · Apollo Bay · Cape Schanck Lighthouse',
            cost: 1078,
            costNote: '2 people',
          },
          { type: 'food', title: 'George’s Takeaway', cost: 190 },
          {
            type: 'stay',
            title: 'Hyatt Centric Melbourne',
            cost: 2863,
            costNote: 'Night 2 of 3 · three-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'apr-2',
        date: 'APR 02',
        day: 'WEDNESDAY',
        place: 'Steam railway, wildlife, and Sodagreen',
        weather: 'Partly cloudy',
        temperature: '13–20°',
        coordinate: [-38.4835, 145.231],
        entries: [
          {
            type: 'visit',
            title: 'Puffing Billy Railway day trip',
            detail: 'Puffing Billy · Maru Koala and Animal Park · Phillip Island',
            cost: 1738,
            costNote: '2 people',
          },
          {
            type: 'visit',
            title: 'Phillip Island nature stops',
            detail: 'Chocolate Factory · Seal Rocks · Penguin Parade',
          },
          {
            type: 'visit',
            title: 'Sodagreen',
            detail: '19:00 · John Cain Arena',
            cost: 1817,
          },
          { type: 'food', title: 'Puffing Billy Railway', cost: 117 },
          {
            type: 'stay',
            title: 'Hyatt Centric Melbourne',
            cost: 2863,
            costNote: 'Night 3 of 3 · three-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'apr-3',
        date: 'APR 03',
        day: 'THURSDAY',
        place: 'Melbourne → Sydney',
        weather: 'Sunny',
        temperature: '11–22°',
        coordinate: [-33.8688, 151.2093],
        entries: [
          {
            type: 'visit',
            title: 'Melbourne city walk',
            detail: 'A final day through the city before the evening flight',
          },
          {
            type: 'flight',
            title: '20:30–21:55 · VA895',
            detail: 'Melbourne T3 (MEL) → Sydney T2 (SYD)',
            cost: 1483,
            costNote: '2 people',
          },
          { type: 'food', title: 'Foglia Di Fico', cost: 1062 },
          {
            type: 'stay',
            title: 'Hyatt Regency Sydney',
            cost: 2300,
            costNote: 'Night 1 of 2 · two-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'apr-4',
        date: 'APR 04',
        day: 'FRIDAY',
        place: 'Sydney city walk',
        weather: 'Partly cloudy',
        temperature: '16–22°',
        coordinate: [-33.8688, 151.2093],
        entries: [
          {
            type: 'visit',
            title: 'Sydney city walk',
            detail: 'Harbour streets, landmarks, and the waterfront',
          },
          { type: 'drive', title: 'Sydney bus', cost: 158 },
          { type: 'drive', title: 'Sydney train', cost: 62 },
          { type: 'food', title: 'Dodee Paidang', cost: 295 },
          { type: 'food', title: 'Toastie Smith', cost: 104 },
          {
            type: 'stay',
            title: 'Hyatt Regency Sydney',
            cost: 2300,
            costNote: 'Night 2 of 2 · two-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'apr-5',
        date: 'APR 05',
        day: 'SATURDAY',
        place: 'Sydney Harbour and JJ Lin',
        weather: 'Sunny',
        temperature: '16–24°',
        coordinate: [-33.8472, 151.0649],
        entries: [
          {
            type: 'visit',
            title: 'Sydney city walk',
            detail: 'A second harbour day before the concert',
          },
          {
            type: 'visit',
            title: 'JJ Lin',
            detail: '20:00 · Qudos Bank Arena',
            cost: 3297,
            costNote: '2 people',
          },
          { type: 'food', title: 'Peter’s Fish Market', cost: 745 },
          {
            type: 'stay',
            title: 'Park Hyatt Sydney',
            cost: 2711,
            costNote: '1 night',
          },
        ],
      },
      {
        id: 'apr-6',
        date: 'APR 06',
        day: 'SUNDAY',
        place: 'Sydney → Beijing',
        weather: 'Sunny',
        temperature: '14–23°',
        coordinate: [-33.9399, 151.1753],
        entries: [
          {
            type: 'visit',
            title: 'Sydney city walk',
            detail: 'One final Sunday around the harbour',
          },
          {
            type: 'flight',
            title: '20:50–05:00 +1 · Sydney → Beijing',
            detail: 'Sydney (SYD) → Beijing Capital (PEK)',
            cost: 7684,
            costNote: 'Return leg · shared round-trip fare',
            costShared: true,
          },
          { type: 'food', title: 'Uber Eats', cost: 318 },
          { type: 'food', title: 'KFC', cost: 108 },
        ],
      },
    ],
  },
  costs: {
    currency: 'CNY',
    summaries: {
      all: { label: 'Trip total · 2 people', total: 53269 },
      flight: { label: 'Flights total · 2 people', total: 9167 },
      drive: { label: 'Ground transport total', total: 1856 },
      food: { label: 'Dining total', total: 4806 },
      stay: { label: 'Stays total', total: 7874 },
      visit: { label: 'Activities total', total: 7930 },
    },
    other: [
      {
        filter: 'food',
        category: 'Dining',
        item: 'Fruit, snacks, and drinks',
        detail: 'Combined trip total',
        cost: 501,
      },
      {
        filter: 'all',
        category: 'Souvenirs',
        item: 'National Gallery of Victoria',
        cost: 368,
      },
      { filter: 'all', category: 'Souvenirs', item: 'Chemist Warehouse', cost: 131 },
      { filter: 'all', category: 'Souvenirs', item: 'Sydney Opera House', cost: 80 },
      { filter: 'all', category: 'Souvenirs', item: 'Duty free at the airport', cost: 1470 },
      {
        filter: 'all',
        category: 'Travel',
        item: 'Australian visas',
        detail: 'CNY 932 each · 2 people',
        cost: 1864,
      },
      {
        filter: 'all',
        category: 'Travel',
        item: 'Phone cards',
        detail: 'CNY 78 each · 2 people',
        cost: 156,
      },
      { filter: 'all', category: 'Purchases', item: 'Aesop', cost: 399 },
      { filter: 'all', category: 'Purchases', item: 'Arc’teryx', cost: 17167 },
    ],
    note:
      'Hotels 7,874 · transport 11,023 · activities 7,930 · dining 4,806 · souvenirs 4,069 · purchases 17,566',
  },
  footer: {
    mark: 'AUSTRALIA / 25',
    note: 'Mapped from eight autumn days across Melbourne and Sydney in 2025.',
  },
};
