import type { TravelConfig } from '../types';

export const franceTrip: TravelConfig = {
  slug: 'france',
  countryName: 'France + Italy + Netherlands + Belgium',
  theme: {
    ink: '#1d1d1b',
    inkRgb: '29, 29, 27',
    cream: '#fff8df',
    creamRgb: '255, 248, 223',
    paper: '#fffdf7',
    paperRgb: '255, 253, 247',
    accent: '#fdda24',
    accentRgb: '253, 218, 36',
    secondary: '#0055a4',
  },
  brand: {
    code: 'FR',
    year: '25',
  },
  home: {
    kicker: 'SEP—OCT 2025',
    title: 'From Paris galleries to Amsterdam canals.',
    description:
      'Eleven autumn days across Paris, Venice, Milan, Amsterdam, and Brussels—museum halls, palace gardens, city rooftops, and canal streets.',
    actionLabel: 'Open the France and Europe itinerary',
  },
  hero: {
    kicker: 'FRANCE + EUROPE · AUTUMN 2025',
    title: ['Museum days,', 'canal nights.'],
    intro:
      'An eleven-day European route led by Paris, then moving through Disneyland, Venice, Milan, Amsterdam, and a Brussels day trip.',
    stamp: {
      number: '11',
      label: 'DAYS ACROSS EUROPE',
      dates: '27 SEP — 07 OCT',
      ariaLabel: 'Trip dates September 27 to October 7, 2025',
    },
    facts: [
      { value: '04', label: 'countries crossed' },
      { value: '05', label: 'flight legs' },
      { value: '09', label: 'hotel nights' },
    ],
  },
  route: {
    kicker: 'THE EUROPE ROUTE',
    title: 'Paris first, then Venice, Milan, Amsterdam, and Brussels.',
    mapAriaLabel: 'Interactive map of the France, Italy, Netherlands, and Belgium itinerary',
    center: [49.1, 6.2],
    zoom: 5,
    minZoom: 4,
    roads: [
      [
        [48.8566, 2.3522],
        [48.8049, 2.1204],
        [48.8566, 2.3522],
        [48.8674, 2.7836],
        [48.7262, 2.3652],
      ],
      [
        [45.4408, 12.3155],
        [45.4642, 9.19],
        [45.4408, 12.3155],
      ],
      [
        [52.3676, 4.9041],
        [50.8503, 4.3517],
        [52.3676, 4.9041],
      ],
    ],
    flights: [
      [
        [48.7262, 2.3652],
        [45.5053, 12.3519],
      ],
      [
        [45.5053, 12.3519],
        [52.3105, 4.7683],
      ],
    ],
  },
  itinerary: {
    kicker: 'DAY BY DAY',
    title: 'The France and Europe itinerary.',
    days: [
      {
        id: 'sep-27',
        date: 'SEP 27',
        day: 'SATURDAY',
        place: 'Beijing → Guangzhou → Paris',
        coordinate: [48.8566, 2.3522],
        entries: [
          {
            type: 'flight',
            title: '18:30–21:45 · CZ3100',
            detail: 'Beijing Daxing (PKX) → Guangzhou T1 (CAN)',
            cost: 22716,
            costNote: 'International round-trip airfare · 2 people',
            costShared: true,
          },
          {
            type: 'flight',
            title: '00:20–06:50 +1 · CZ347',
            detail: 'Guangzhou T1 (CAN) → Paris Charles de Gaulle T1 (CDG)',
          },
        ],
      },
      {
        id: 'sep-28',
        date: 'SEP 28',
        day: 'SUNDAY',
        place: 'Paris museums and gardens',
        weather: 'Partly cloudy',
        temperature: '7–19°',
        coordinate: [48.8606, 2.3376],
        entries: [
          { type: 'visit', title: 'Notre-Dame de Paris' },
          {
            type: 'visit',
            title: 'Paris Museum Pass',
            detail: 'Musée de l’Orangerie at 12:30 · Musée d’Orsay',
            cost: 1224,
            costNote: '2 people',
          },
          {
            type: 'visit',
            title: 'Tuileries Garden and Place de la Concorde',
          },
          {
            type: 'drive',
            title: 'Paris Métro',
            detail: 'Combined trip total',
            cost: 746,
            costShared: true,
          },
          { type: 'food', title: 'Kozy Notre Dame', cost: 496 },
          { type: 'food', title: 'Com', cost: 608 },
          {
            type: 'stay',
            title: 'Hotel du Louvre',
            cost: 9373,
            costNote: 'Night 1 of 3 · three-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'sep-29',
        date: 'SEP 29',
        day: 'MONDAY',
        place: 'The Louvre and grand Paris',
        weather: 'Sunny',
        temperature: '8–19°',
        coordinate: [48.8738, 2.295],
        entries: [
          {
            type: 'visit',
            title: 'Sainte-Chapelle',
            detail: 'Timed entry at 09:00',
          },
          {
            type: 'visit',
            title: 'Notre-Dame rooftop tour',
            detail: 'Timed entry at 10:30',
          },
          {
            type: 'visit',
            title: 'Louvre Museum',
            detail: 'Timed entry at 12:00',
          },
          {
            type: 'visit',
            title: 'Champs-Élysées and Arc de Triomphe',
            detail: 'Avenue walk · rooftop tour',
          },
          {
            type: 'drive',
            title: 'Uber',
            detail: 'Combined trip total',
            cost: 1787,
            costShared: true,
          },
          { type: 'food', title: 'Louvre Café', cost: 301 },
          { type: 'food', title: 'Uber Eats', cost: 265 },
          {
            type: 'stay',
            title: 'Hotel du Louvre',
            cost: 9373,
            costNote: 'Night 2 of 3 · three-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'sep-30',
        date: 'SEP 30',
        day: 'TUESDAY',
        place: 'Versailles and the Seine',
        weather: 'Partly cloudy',
        temperature: '9–19°',
        coordinate: [48.8049, 2.1204],
        entries: [
          {
            type: 'visit',
            title: 'Palace of Versailles',
            detail: 'Palace at 09:00 · Estate of Trianon at 12:00',
          },
          {
            type: 'visit',
            title: 'Versailles Gardens',
            cost: 185,
            costNote: '2 people',
          },
          { type: 'visit', title: 'Eiffel Tower' },
          {
            type: 'visit',
            title: 'Seine River cruise',
            detail: 'Bateaux Parisiens at 18:00',
            cost: 107,
            costNote: '2 people',
          },
          {
            type: 'visit',
            title: 'Crazy Horse Paris',
            detail: 'Show at 20:00',
            cost: 2010,
            costNote: '2 people',
          },
          { type: 'food', title: 'Versailles Café', cost: 88 },
          { type: 'food', title: 'Crazy Horse drink', cost: 84 },
          { type: 'food', title: 'Relais', cost: 807 },
          {
            type: 'stay',
            title: 'Hotel du Louvre',
            cost: 9373,
            costNote: 'Night 3 of 3 · three-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'oct-1',
        date: 'OCT 01',
        day: 'WEDNESDAY',
        place: 'Paris → Disneyland Paris',
        weather: 'Sunny',
        temperature: '8–19°',
        coordinate: [48.8674, 2.7836],
        entries: [
          { type: 'visit', title: 'Palais Garnier' },
          {
            type: 'visit',
            title: 'Paris shopping walk',
            detail: 'Galeries Lafayette · Printemps · Le Marais',
          },
          { type: 'food', title: 'McDonald’s Louvre', cost: 210 },
          { type: 'food', title: 'Printemps Café', cost: 87 },
          { type: 'food', title: 'Pho', cost: 318 },
          {
            type: 'stay',
            title: 'Disney Sequoia Lodge',
            detail: 'Disneyland Paris package',
            cost: 3223,
            costNote: 'Night 1 of 2 · package total',
            costShared: true,
          },
        ],
      },
      {
        id: 'oct-2',
        date: 'OCT 02',
        day: 'THURSDAY',
        place: 'Disneyland Paris',
        weather: 'Sunny',
        temperature: '8–20°',
        coordinate: [48.8674, 2.7836],
        entries: [
          {
            type: 'visit',
            title: 'Disneyland Paris',
            detail: 'Three-day admission package',
            cost: 2600,
            costNote: '2 people',
          },
          { type: 'food', title: 'Disneyland Paris dining', cost: 1367 },
          {
            type: 'stay',
            title: 'Disney Sequoia Lodge',
            detail: 'Disneyland Paris package',
            cost: 3223,
            costNote: 'Night 2 of 2 · package total',
            costShared: true,
          },
        ],
      },
      {
        id: 'oct-3',
        date: 'OCT 03',
        day: 'FRIDAY',
        place: 'Paris → Venice',
        weather: 'Cloudy',
        temperature: '9–18°',
        coordinate: [45.4408, 12.3155],
        entries: [
          {
            type: 'drive',
            title: '10:40 · Disneyland Paris → Orly Airport',
            detail: 'Airport bus',
            cost: 404,
          },
          { type: 'food', title: 'McDonald’s Orly Airport', cost: 198 },
          {
            type: 'flight',
            title: '14:25–16:05 · Paris → Venice',
            detail: 'Paris Orly T1 (ORY) → Venice Marco Polo (VCE)',
            cost: 1494,
            costNote: '2 people',
          },
          {
            type: 'drive',
            title: 'Venice boat transport',
            detail: 'Combined trip total',
            cost: 740,
            costShared: true,
          },
          { type: 'food', title: 'Venice Airport Café', cost: 58 },
          { type: 'food', title: 'Osteria AL Venice', cost: 769 },
          {
            type: 'stay',
            title: 'Hyatt Centric Murano Venice',
            cost: 1620,
            costNote: 'Night 1 of 2 · two-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'oct-4',
        date: 'OCT 04',
        day: 'SATURDAY',
        place: 'Venice ↔ Milan',
        weather: 'Partly cloudy',
        temperature: '9–17°',
        coordinate: [45.4642, 9.19],
        entries: [
          {
            type: 'drive',
            title: '10:57–13:25 · Venice → Milan',
            detail: 'Venezia Santa Lucia → Milano Centrale',
            cost: 623,
            costNote: '2 people',
          },
          {
            type: 'visit',
            title: 'Duomo di Milano',
            detail: 'Timed entry at 15:00',
            cost: 168,
            costNote: '2 people',
          },
          {
            type: 'visit',
            title: 'Leonardo’s Last Supper Museum',
            detail: 'Timed entry at 16:45',
            cost: 408,
            costNote: '2 people',
          },
          {
            type: 'drive',
            title: '18:20–21:42 · Milan → Venice',
            detail: 'Milano Porta Garibaldi → Venezia Santa Lucia',
            cost: 570,
            costNote: '2 people',
          },
          { type: 'food', title: 'Osteria Papa Milan', cost: 807 },
          { type: 'food', title: 'Ciacco Gelato', cost: 67 },
          { type: 'food', title: 'Venchi Gelato', cost: 111 },
          { type: 'food', title: 'McDonald’s Milan', cost: 301 },
          {
            type: 'stay',
            title: 'Hyatt Centric Murano Venice',
            cost: 1620,
            costNote: 'Night 2 of 2 · two-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'oct-5',
        date: 'OCT 05',
        day: 'SUNDAY',
        place: 'Venice → Amsterdam',
        weather: 'Cloudy',
        temperature: '11–17°',
        coordinate: [52.3676, 4.9041],
        entries: [
          {
            type: 'visit',
            title: 'Venice landmarks',
            detail: 'Grand Canal · St Mark’s Campanile',
          },
          { type: 'food', title: 'Kims So Korean', cost: 569 },
          { type: 'food', title: 'Venice Airport Pizza', cost: 172 },
          {
            type: 'flight',
            title: '16:15–18:20 · Venice → Amsterdam',
            detail: 'Venice Marco Polo (VCE) → Amsterdam Schiphol (AMS)',
            cost: 2260,
            costNote: '2 people',
          },
          { type: 'visit', title: 'Damrak', detail: 'Amsterdam arrival walk' },
          {
            type: 'stay',
            title: 'Hyatt Regency Amsterdam',
            cost: 4290,
            costNote: 'Night 1 of 2 · two-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'oct-6',
        date: 'OCT 06',
        day: 'MONDAY',
        place: 'Amsterdam ↔ Brussels',
        weather: 'Rainy',
        temperature: '8–15°',
        coordinate: [50.8503, 4.3517],
        entries: [
          {
            type: 'drive',
            title: '10:30–13:15 · Amsterdam → Brussels',
            detail: 'Amsterdam Centraal → Brussels-North',
            cost: 252,
            costNote: '2 people',
          },
          {
            type: 'visit',
            title: 'Brussels city walk',
            detail: 'Manneken Pis · Grand Place',
          },
          {
            type: 'drive',
            title: '18:30–21:00 · Brussels → Amsterdam',
            detail: 'Brussels-North → Amsterdam Sloterdijk',
            cost: 325,
            costNote: '2 people',
          },
          { type: 'food', title: 'Brussels beer and fries', cost: 225 },
          { type: 'food', title: 'Ramen', cost: 430 },
          { type: 'food', title: 'Burger at Amsterdam Centraal', cost: 38 },
          {
            type: 'stay',
            title: 'Hyatt Regency Amsterdam',
            cost: 4290,
            costNote: 'Night 2 of 2 · two-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'oct-7',
        date: 'OCT 07',
        day: 'TUESDAY',
        place: 'Amsterdam → Beijing',
        weather: 'Partly cloudy',
        temperature: '11–18°',
        coordinate: [52.3105, 4.7683],
        entries: [
          {
            type: 'visit',
            title: 'Amsterdam centre',
            detail: 'Damrak · Dam Square',
          },
          {
            type: 'visit',
            title: 'Van Gogh Museum',
            cost: 402,
            costNote: '2 people',
          },
          { type: 'food', title: 'Starbucks', cost: 114 },
          { type: 'food', title: 'McDonald’s Amsterdam', cost: 182 },
          { type: 'food', title: 'Schiphol Airport Sushi', cost: 206 },
          {
            type: 'flight',
            title: '20:40–12:40 +1 · CZ346',
            detail: 'Amsterdam Schiphol (AMS) → Beijing Daxing (PKX)',
          },
        ],
      },
    ],
  },
  costs: {
    currency: 'CNY',
    summaries: {
      all: { label: 'Trip total · 2 people · purchases excluded', total: 69043 },
      flight: { label: 'Flights total · 2 people', total: 26470 },
      drive: { label: 'Ground transport total', total: 5446 },
      food: { label: 'Dining total', total: 9098 },
      stay: { label: 'Stays total', total: 18506 },
      visit: { label: 'Activities total', total: 7104 },
    },
    other: [
      {
        filter: 'food',
        category: 'Dining',
        item: 'Snacks and drinks',
        detail: 'Combined trip total',
        cost: 219,
      },
      { filter: 'all', category: 'Souvenirs', item: 'Notre-Dame', cost: 80 },
      { filter: 'all', category: 'Souvenirs', item: 'Musée d’Orsay', cost: 166 },
      { filter: 'all', category: 'Souvenirs', item: 'Sainte-Chapelle', cost: 49 },
      { filter: 'all', category: 'Souvenirs', item: 'Louvre Museum', cost: 484 },
      { filter: 'all', category: 'Souvenirs', item: 'Crazy Horse', cost: 50 },
      { filter: 'all', category: 'Souvenirs', item: 'Pharmacy', cost: 87 },
      { filter: 'all', category: 'Souvenirs', item: 'Last Supper Museum', cost: 83 },
      { filter: 'all', category: 'Souvenirs', item: 'Murano glass', cost: 420 },
      { filter: 'all', category: 'Souvenirs', item: 'Van Gogh Museum', cost: 251 },
      { filter: 'all', category: 'Souvenirs', item: 'Schiphol Airport duty free', cost: 747 },
    ],
    note:
      'Hotels 18,506 · transport 31,916 · activities 7,104 · dining 9,098 · souvenirs 2,418',
  },
  footer: {
    mark: 'FRANCE + EUROPE / 25',
    note: 'Mapped from eleven autumn days across France, Italy, the Netherlands, and Belgium.',
  },
};
