import type { TravelConfig } from '../types';

export const italyTrip: TravelConfig = {
  slug: 'italy',
  countryName: 'Italy + South of France',
  theme: {
    ink: '#6f1d1b',
    inkRgb: '111, 29, 27',
    cream: '#fff7e8',
    creamRgb: '255, 247, 232',
    paper: '#fffdf8',
    paperRgb: '255, 253, 248',
    accent: '#7ed6d1',
    accentRgb: '126, 214, 209',
    secondary: '#008c45',
  },
  brand: {
    code: 'IT',
    year: '26',
  },
  home: {
    kicker: 'APR—MAY 2026',
    title: 'From Riviera light to Roman stone.',
    description:
      'Ten spring days from Nice to the Dolomites, Florence, and Rome—alpine roads, Renaissance galleries, Tuscan trains, and ancient streets.',
    actionLabel: 'Open the Italy itinerary',
  },
  hero: {
    kicker: 'ITALY + SOUTHERN FRANCE · SPRING 2026',
    title: ['Alpine roads,', 'Roman stone.'],
    intro:
      'A ten-day journey from the Côte d’Azur through the Dolomites and Florence, ending among Vatican galleries and the monuments of Rome.',
    stamp: {
      number: '10',
      label: 'DAYS SOUTHBOUND',
      dates: '25 APR — 04 MAY',
      ariaLabel: 'Trip dates April 25 to May 4, 2026',
    },
    facts: [
      { value: '02', label: 'countries crossed' },
      { value: '04', label: 'hotel bases' },
      { value: '09', label: 'nights away' },
    ],
  },
  route: {
    kicker: 'THE ITALY ROUTE',
    title: 'Nice, the Dolomites, Florence, then Rome.',
    mapAriaLabel: 'Interactive map of the Italy and South of France itinerary',
    center: [44.4, 9.8],
    zoom: 5,
    minZoom: 4,
    roads: [
      [
        [45.5053, 12.3519],
        [46.642, 11.7],
        [46.5405, 11.617],
        [46.5992, 11.7243],
        [46.4983, 11.3548],
      ],
      [
        [46.4983, 11.3548],
        [43.7696, 11.2558],
        [43.7228, 10.4017],
        [43.7696, 11.2558],
        [41.9028, 12.4964],
      ],
    ],
    flights: [
      [
        [43.6653, 7.215],
        [45.5053, 12.3519],
      ],
    ],
  },
  itinerary: {
    kicker: 'DAY BY DAY',
    title: 'The Italy itinerary.',
    days: [
      {
        id: 'apr-25',
        date: 'APR 25',
        day: 'SATURDAY',
        place: 'Beijing → Frankfurt → Nice',
        weather: 'Partly cloudy',
        temperature: '12–24°',
        coordinate: [43.7102, 7.262],
        entries: [
          {
            type: 'flight',
            title: '09:55–14:15 · CA957',
            detail: 'Beijing Capital T3 (PEK) → Frankfurt T1 (FRA)',
            cost: 15438,
            costNote: 'International round-trip airfare · 2 people',
            costShared: true,
          },
          {
            type: 'flight',
            title: '16:40–18:10 · LH1064',
            detail: 'Frankfurt T1 (FRA) → Nice T1 (NCE)',
          },
          { type: 'food', title: 'Hausmann’s Flughafen', cost: 312 },
          { type: 'food', title: 'Restaurant Titi', cost: 376 },
          { type: 'food', title: 'Starbucks', cost: 108 },
          {
            type: 'stay',
            title: 'AC Hotel Nice',
            cost: 3713,
            costNote: 'Night 1 of 2 · two-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'apr-26',
        date: 'APR 26',
        day: 'SUNDAY',
        place: 'Nice',
        weather: 'Partly cloudy',
        temperature: '13–21°',
        coordinate: [43.7102, 7.262],
        entries: [
          {
            type: 'visit',
            title: 'Nice city walk',
            detail: 'A full Riviera day without a fixed route',
          },
          {
            type: 'drive',
            title: 'Uber',
            detail: 'Combined trip total · 11 rides',
            cost: 1511,
            costShared: true,
          },
          { type: 'food', title: 'SARL Le Village', cost: 692 },
          { type: 'food', title: 'Gusti', cost: 456 },
          {
            type: 'stay',
            title: 'AC Hotel Nice',
            cost: 3713,
            costNote: 'Night 2 of 2 · two-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'apr-27',
        date: 'APR 27',
        day: 'MONDAY',
        place: 'Nice → Venice → Funes',
        weather: 'Partly cloudy',
        temperature: '13–23°',
        coordinate: [46.642, 11.7],
        entries: [
          {
            type: 'flight',
            title: '10:45–11:55 · EJU1697',
            detail: 'Nice T2 (NCE) → Venice Marco Polo (VCE)',
            cost: 1512,
            costNote: '2 people',
          },
          {
            type: 'drive',
            title: 'Pick up rental car · 12:30',
            detail: 'Venice Airport · approximately 232 km and 2 hr 45 min to Funes',
            cost: 2039,
          },
          {
            type: 'drive',
            title: 'Road-trip fuel, tolls, and parking',
            detail: 'Combined trip totals',
            cost: 1090,
            costNote: 'Fuel 467 · tolls 238 · parking 385',
            costShared: true,
          },
          { type: 'visit', title: 'Funes' },
          { type: 'food', title: 'Nice Airport Terminal 2', cost: 140 },
          {
            type: 'food',
            title: 'McDonald’s',
            detail: 'Three visits · combined trip total',
            cost: 690,
            costShared: true,
          },
          { type: 'food', title: 'Isaan Coffee & More', cost: 448 },
          {
            type: 'stay',
            title: 'Parkhotel Mondschein',
            cost: 3546,
            costNote: 'Night 1 of 2 · two-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'apr-28',
        date: 'APR 28',
        day: 'TUESDAY',
        place: 'Alpe di Siusi and Seceda',
        weather: 'Cloudy',
        temperature: '13–23°',
        coordinate: [46.5992, 11.7243],
        entries: [
          {
            type: 'visit',
            title: 'Alpe di Siusi',
            detail: 'Cable-car morning in the Dolomites',
          },
          {
            type: 'visit',
            title: 'Seceda',
            detail: 'High-alpine afternoon',
          },
          {
            type: 'drive',
            title: 'Local buses',
            detail: 'Six rides · combined trip total',
            cost: 63,
          },
          { type: 'food', title: 'Snetonstube', cost: 748 },
          {
            type: 'stay',
            title: 'Parkhotel Mondschein',
            cost: 3546,
            costNote: 'Night 2 of 2 · two-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'apr-29',
        date: 'APR 29',
        day: 'WEDNESDAY',
        place: 'Bolzano → Florence',
        weather: 'Partly cloudy',
        temperature: '12–23°',
        coordinate: [43.7696, 11.2558],
        entries: [
          {
            type: 'drive',
            title: 'Return rental car · 12:30',
            detail: 'Bolzano downtown',
          },
          {
            type: 'drive',
            title: '14:42–17:54 · Bolzano → Florence',
            detail: 'Bolzano → Firenze Santa Maria Novella',
          },
          { type: 'food', title: 'Autogrill', cost: 100 },
          { type: 'food', title: 'Ristorante Bamboo Bolzano', cost: 636 },
          {
            type: 'stay',
            title: 'Hotel Indigo Florence',
            cost: 3490,
            costNote: 'Night 1 of 2 · two-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'apr-30',
        date: 'APR 30',
        day: 'THURSDAY',
        place: 'Florence ↔ Pisa',
        weather: 'Partly cloudy',
        temperature: '11–23°',
        coordinate: [43.7228, 10.4017],
        entries: [
          {
            type: 'drive',
            title: '09:53–11:19 · Florence → Pisa',
            detail: 'Firenze Santa Maria Novella → Pisa San Rossore',
          },
          { type: 'visit', title: 'Leaning Tower of Pisa' },
          {
            type: 'drive',
            title: '14:27–15:35 · Pisa → Florence',
            detail: 'Pisa Centrale → Firenze Santa Maria Novella',
          },
          {
            type: 'visit',
            title: 'Galleria dell’Accademia di Firenze',
            detail: 'Timed entry at 15:45',
            cost: 478,
            costNote: '2 people',
          },
          { type: 'visit', title: 'Piazzale Michelangelo' },
          { type: 'food', title: 'Trattoria Zà Zà', cost: 1177 },
          { type: 'food', title: 'Principe della Carne Firenze', cost: 572 },
          {
            type: 'stay',
            title: 'Hotel Indigo Florence',
            cost: 3490,
            costNote: 'Night 2 of 2 · two-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'may-1',
        date: 'MAY 01',
        day: 'FRIDAY',
        place: 'Florence → Rome',
        weather: 'Rainy',
        temperature: '13–23°',
        coordinate: [41.9028, 12.4964],
        entries: [
          {
            type: 'visit',
            title: 'Uffizi Galleries',
            detail: 'Timed entry at 10:00',
            cost: 395,
            costNote: '2 people',
          },
          {
            type: 'visit',
            title: 'Florence landmarks',
            detail: 'Cathedral of Santa Maria del Fiore · Piazza della Signoria · Ponte Vecchio',
          },
          {
            type: 'visit',
            title: 'Boboli Gardens',
            cost: 160,
            costNote: '2 people',
          },
          {
            type: 'drive',
            title: '16:03–17:40 · Florence → Rome',
            detail: 'Firenze Santa Maria Novella → Roma Termini',
          },
          {
            type: 'drive',
            title: 'Italian train travel',
            detail: 'Fourteen tickets · combined trip total',
            cost: 1641,
            costShared: true,
          },
          { type: 'food', title: 'Luna Restaurant', cost: 809 },
          {
            type: 'stay',
            title: 'Hilton Garden Inn Rome Colosseum',
            cost: 428,
            costNote: 'Night 1 of 3 · three-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'may-2',
        date: 'MAY 02',
        day: 'SATURDAY',
        place: 'Vatican City',
        weather: 'Partly cloudy',
        temperature: '13–24°',
        coordinate: [41.9029, 12.4534],
        entries: [
          {
            type: 'visit',
            title: 'Vatican Museums',
            detail: 'Timed entry at 11:00',
            cost: 412,
            costNote: '2 people',
          },
          {
            type: 'visit',
            title: 'Saint Peter’s Basilica',
            cost: 112,
            costNote: '2 people',
          },
          { type: 'food', title: 'Musei Vaticani Ristora', cost: 248 },
          { type: 'food', title: 'That’s Vero Amore Roma', cost: 384 },
          {
            type: 'stay',
            title: 'Hilton Garden Inn Rome Colosseum',
            cost: 428,
            costNote: 'Night 2 of 3 · three-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'may-3',
        date: 'MAY 03',
        day: 'SUNDAY',
        place: 'Rome',
        weather: 'Partly cloudy',
        temperature: '14–24°',
        coordinate: [41.9028, 12.4964],
        entries: [
          {
            type: 'visit',
            title: 'Rome city walk',
            detail: 'Piazza del Popolo · Piazza di Spagna · Pantheon · Piazza Navona',
          },
          {
            type: 'visit',
            title: 'Trevi Fountain',
            cost: 32,
            costNote: '2 people',
          },
          {
            type: 'drive',
            title: 'Scooter rides',
            detail: 'Four rides · combined trip total',
            cost: 187,
          },
          { type: 'food', title: 'Osteria Vecchio Vicolo', cost: 912 },
          { type: 'food', title: 'Saltimbocca', cost: 456 },
          {
            type: 'stay',
            title: 'Hilton Garden Inn Rome Colosseum',
            cost: 428,
            costNote: 'Night 3 of 3 · three-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'may-4',
        date: 'MAY 04',
        day: 'MONDAY',
        place: 'Rome → Beijing',
        weather: 'Partly cloudy',
        temperature: '11–21°',
        coordinate: [41.8003, 12.2389],
        entries: [
          {
            type: 'visit',
            title: 'Colosseum',
            detail: 'Timed entry at 11:45',
            cost: 287,
            costNote: '2 people',
          },
          { type: 'visit', title: 'Roman Forum' },
          { type: 'food', title: 'Pizza Forum', cost: 580 },
          { type: 'food', title: 'Iari The Vino / Iannelli', cost: 620 },
          {
            type: 'flight',
            title: '20:55–12:55 +1 · CA940',
            detail: 'Rome Fiumicino T3 (FCO) → Beijing Capital T3 (PEK)',
          },
        ],
      },
    ],
  },
  costs: {
    currency: 'CNY',
    summaries: {
      all: { label: 'Trip total · 2 people · purchases excluded', total: 48566 },
      flight: { label: 'Flights total · 2 people', total: 16950 },
      drive: { label: 'Ground transport total', total: 6531 },
      food: { label: 'Dining total', total: 10933 },
      stay: { label: 'Stays total', total: 11177 },
      visit: { label: 'Activities total', total: 1876 },
    },
    other: [
      {
        filter: 'food',
        category: 'Dining',
        item: 'Snacks and drinks',
        detail: 'Twelve stops · combined trip total',
        cost: 469,
      },
      { filter: 'all', category: 'Souvenirs', item: 'Pantheon Gift Shop', cost: 48 },
      { filter: 'all', category: 'Souvenirs', item: 'Florence Bookshop', cost: 64 },
      { filter: 'all', category: 'Souvenirs', item: 'Florence Cathedral Bookshop', cost: 40 },
      { filter: 'all', category: 'Souvenirs', item: 'Florence Gallery Bookshop', cost: 71 },
      { filter: 'all', category: 'Souvenirs', item: 'Vatican Gift Shop', cost: 76 },
      { filter: 'all', category: 'Souvenirs', item: 'Vatican Museums Bookshop', cost: 40 },
      { filter: 'all', category: 'Souvenirs', item: 'Colosseum Bookshop', cost: 47 },
      { filter: 'all', category: 'Souvenirs', item: 'Duty free', cost: 160 },
      { filter: 'all', category: 'Souvenirs', item: 'Venchi', detail: '2 purchases', cost: 553 },
    ],
    note:
      'Hotels 11,177 · transport 23,481 · activities 1,876 · dining 10,933 · souvenirs 1,099',
  },
  footer: {
    mark: 'ITALY + RIVIERA / 26',
    note: 'Mapped from ten spring days across southern France and Italy in 2026.',
  },
};
