import type { TravelConfig } from '../types';

const totalTripCost = 35519;

export const newZealandTrip: TravelConfig = {
  slug: 'newzealand',
  countryName: 'New Zealand',
  theme: {
    ink: '#122b25',
    inkRgb: '18, 43, 37',
    cream: '#f4eddd',
    creamRgb: '244, 237, 221',
    paper: '#fffaf0',
    paperRgb: '255, 250, 240',
    accent: '#e65b37',
    accentRgb: '230, 91, 55',
    secondary: '#b9c9b7',
  },
  brand: {
    code: 'NZ',
    year: '23',
  },
  home: {
    kicker: 'FIELD NOTE · MAY 2023',
    title: 'Aotearoa, from harbour lights to alpine skies.',
    description:
      'An interactive record of nine days across Aotearoa—from Auckland’s harbour to Tekapo’s dark skies, Aoraki / Mount Cook, and rain-softened Queenstown.',
    actionLabel: 'Open the interactive itinerary',
  },
  hero: {
    kicker: 'AOTEAROA · AUTUMN 2023',
    title: ['Southbound,', 'under open skies.'],
    intro:
      'Auckland’s harbour opened the journey, but the South Island stole the show — Lake Tekapo’s dark skies, the road beneath Aoraki / Mount Cook, and rain-softened Queenstown.',
    stamp: {
      number: '09',
      label: 'DAYS ON THE ROAD',
      dates: '28 APR — 06 MAY',
      ariaLabel: 'Trip dates April 28 to May 6, 2023',
    },
    facts: [
      { value: '696', label: 'km by road' },
      { value: '06', label: 'flight legs' },
      { value: '08', label: 'nights away' },
    ],
  },
  route: {
    kicker: 'THE ROUTE',
    title: 'Across Aotearoa, one stop at a time.',
    mapAriaLabel: 'Interactive map of the New Zealand itinerary',
    center: [-41.35, 172.2],
    zoom: 5,
    minZoom: 4,
    road: [
      [-43.5321, 172.6362],
      [-44.0047, 170.4771],
      [-43.734, 170.096],
      [-44.0047, 170.4771],
      [-44.611, 169.257],
      [-45.0312, 168.6626],
    ],
    flights: [
      [
        [-36.8509, 174.7645],
        [-43.5321, 172.6362],
      ],
      [
        [-45.0312, 168.6626],
        [-36.8509, 174.7645],
      ],
    ],
  },
  itinerary: {
    kicker: 'DAY BY DAY',
    title: 'The full itinerary.',
    days: [
      {
        id: 'apr-28',
        date: 'APR 28',
        day: 'FRIDAY',
        place: 'Beijing → Auckland',
        weather: 'Cloudy',
        temperature: '15–20°',
        coordinate: [-36.8509, 174.7645],
        entries: [
          {
            type: 'flight',
            title: '17:15–19:20 · MU5138',
            detail: 'Beijing Daxing (PKX) → Shanghai Pudong T1 (PVG)',
            cost: 10632,
            costNote: 'Round-trip airfare · 2 people',
            costShared: true,
          },
          {
            type: 'flight',
            title: '00:15–15:45 · MU779',
            detail: 'Shanghai Pudong T1 (PVG) → Auckland (AKL)',
            cost: 10632,
            costNote: 'Round-trip airfare · 2 people',
            costShared: true,
          },
          { type: 'stay', title: 'voco Auckland', cost: 1103, costNote: '1 night' },
        ],
      },
      {
        id: 'apr-29',
        date: 'APR 29',
        day: 'SATURDAY',
        place: 'Auckland → Christchurch',
        weather: 'Sunny',
        temperature: '8–20°',
        coordinate: [-43.5321, 172.6362],
        entries: [
          {
            type: 'flight',
            title: '13:00–14:25 · NZ543',
            detail: 'Auckland (AKL) → Christchurch (CHC)',
            cost: 1540,
            costNote: '2 travelers',
          },
          { type: 'food', title: 'Fiddlesticks Restaurant & Bar' },
          { type: 'food', title: 'Countdown Moorhouse' },
          { type: 'stay', title: 'Crowne Plaza Christchurch', cost: 797, costNote: '1 night' },
        ],
      },
      {
        id: 'apr-30',
        date: 'APR 30',
        day: 'SUNDAY',
        place: 'Christchurch → Lake Tekapo',
        weather: 'Partly cloudy',
        temperature: '7–15°',
        coordinate: [-44.0047, 170.4771],
        entries: [
          {
            type: 'drive',
            title: 'Christchurch → Lake Tekapo',
            detail: '222 km · 2 hr 50 min',
          },
          { type: 'food', title: 'Little Pom’s Café' },
          { type: 'food', title: 'Tekapo Lake View Bar' },
          { type: 'food', title: 'Four Square Tekapo' },
          { type: 'stay', title: 'Peppers Bluewater Resort', cost: 1044, costNote: 'Night 1 of 2' },
        ],
      },
      {
        id: 'may-1',
        date: 'MAY 01',
        day: 'MONDAY',
        place: 'Aoraki / Mount Cook',
        weather: 'Cloudy',
        temperature: '5–10°',
        coordinate: [-43.734, 170.096],
        entries: [
          {
            type: 'drive',
            title: 'Lake Tekapo → Aoraki / Mount Cook',
            detail: '96.2 km · 1 hr 5 min',
          },
          {
            type: 'drive',
            title: 'Aoraki / Mount Cook → Lake Tekapo',
            detail: '96.2 km · 1 hr 5 min',
          },
          { type: 'food', title: 'The Greedy Cow Café' },
          { type: 'visit', title: 'Dark Sky Project' },
          { type: 'stay', title: 'Peppers Bluewater Resort', cost: 1044, costNote: 'Night 2 of 2' },
        ],
      },
      {
        id: 'may-2',
        date: 'MAY 02',
        day: 'TUESDAY',
        place: 'Tekapo → Queenstown',
        weather: 'Rainy',
        temperature: '9–14°',
        coordinate: [-44.611, 169.257],
        entries: [
          {
            type: 'drive',
            title: 'Lake Tekapo → Lake Hāwea',
            detail: '202 km · 2 hr 20 min',
          },
          {
            type: 'drive',
            title: 'Lake Hāwea → Queenstown',
            detail: '80 km · 1 hr 15 min',
          },
          { type: 'food', title: 'High Country Salmon' },
          { type: 'food', title: 'Flame Bar & Grill' },
          { type: 'food', title: 'Four Square Queenstown' },
          { type: 'stay', title: 'Oaks Queenstown Shores Resort', cost: 1055, costNote: '1 night' },
        ],
      },
      {
        id: 'may-3',
        date: 'MAY 03',
        day: 'WEDNESDAY',
        place: 'Queenstown',
        weather: 'Rainy',
        temperature: '10–15°',
        coordinate: [-45.0312, 168.6626],
        entries: [
          { type: 'visit', title: 'Deer Park Heights', cost: 235 },
          { type: 'food', title: 'Saigon Kingdom' },
          { type: 'stay', title: 'Crowne Plaza Queenstown', cost: 1216, costNote: 'Night 1 of 2' },
        ],
      },
      {
        id: 'may-4',
        date: 'MAY 04',
        day: 'THURSDAY',
        place: 'Queenstown',
        weather: 'Rainy',
        temperature: '8–12°',
        coordinate: [-45.0312, 168.6626],
        entries: [
          { type: 'stay', title: 'Crowne Plaza Queenstown', cost: 1216, costNote: 'Night 2 of 2' },
        ],
      },
      {
        id: 'may-5',
        date: 'MAY 05',
        day: 'FRIDAY',
        place: 'Queenstown → Auckland',
        weather: 'Rainy',
        temperature: '16–21°',
        coordinate: [-36.8509, 174.7645],
        entries: [
          {
            type: 'flight',
            title: '09:40–11:30 · NZ614',
            detail: 'Queenstown (ZQN) → Auckland (AKL)',
            cost: 1352,
            costNote: '2 travelers',
          },
          { type: 'stay', title: 'Park Hyatt Auckland', cost: 2559, costNote: '1 night' },
        ],
      },
      {
        id: 'may-6',
        date: 'MAY 06',
        day: 'SATURDAY',
        place: 'Auckland → Beijing',
        coordinate: [-36.8509, 174.7645],
        entries: [
          {
            type: 'flight',
            title: '21:00–05:30 +1 · MU780',
            detail: 'Auckland (AKL) → Shanghai Pudong T1 (PVG)',
            cost: 10632,
            costNote: 'Round-trip airfare · 2 people',
            costShared: true,
          },
          {
            type: 'flight',
            title: '09:05–11:20 +1 · MU5129',
            detail: 'Shanghai Pudong T1 (PVG) → Beijing Daxing (PKX)',
            cost: 10632,
            costNote: 'Round-trip airfare · 2 people',
            costShared: true,
          },
        ],
      },
    ],
  },
  costs: {
    currency: 'CNY',
    summaries: {
      all: { label: 'Trip total · 2 people', total: totalTripCost },
      flight: { label: 'Flights total · 2 people', total: 13524 },
      drive: { label: 'Road trip total · 2 people', total: 4199 },
      food: { label: 'Food total · 2 people', total: 5805 },
      stay: { label: 'Stays total · 2 people', total: 10034 },
      visit: { label: 'Experiences total · 2 people', total: 235 },
    },
    other: [
      { filter: 'drive', category: 'Transport', item: 'AVIS rental car', detail: '5 days', cost: 1975 },
      { filter: 'drive', category: 'Transport', item: 'Fuel refills', detail: '2 refills', cost: 716 },
      { filter: 'drive', category: 'Transport', item: 'Uber', cost: 1436 },
      { filter: 'drive', category: 'Transport', item: 'Ferry', detail: '4 rides', cost: 72 },
      { filter: 'food', category: 'Dining', item: 'Food, beverages & supermarkets', cost: 5805 },
      { filter: 'all', category: 'Souvenirs', item: 'Honey, skincare & chocolates', cost: 1566 },
      { filter: 'all', category: 'Souvenirs', item: 'Phone cards', detail: '2 cards', cost: 156 },
    ],
  },
  footer: {
    mark: 'NZ / 23',
    note: 'Mapped from nine days on the road in May 2023.',
  },
};
