import type { TravelConfig } from '../types';

export const spainPortugalTrip: TravelConfig = {
  slug: 'spain',
  countryName: 'Spain + Portugal',
  theme: {
    ink: '#004225',
    inkRgb: '0, 66, 37',
    cream: '#fff8dc',
    creamRgb: '255, 248, 220',
    paper: '#fffdf5',
    paperRgb: '255, 253, 245',
    accent: '#f1bf00',
    accentRgb: '241, 191, 0',
    secondary: '#aa151b',
  },
  brand: {
    code: 'IB',
    year: '25',
  },
  home: {
    kicker: 'MAY 2025',
    title: 'From Madrid museums to Lisbon light.',
    description:
      'Nine spring days across Madrid, Barcelona, Seville, Granada, and Lisbon—masterpieces, palaces, Gaudí, and Atlantic streets.',
    actionLabel: 'Open the Spain and Portugal itinerary',
  },
  hero: {
    kicker: 'SPAIN + PORTUGAL · SPRING 2025',
    title: ['Art cities,', 'Atlantic light.'],
    intro:
      'A nine-day route through Madrid’s galleries, Barcelona’s Gaudí landmarks, Andalusian palaces, and one final day on Lisbon’s hills.',
    stamp: {
      number: '09',
      label: 'DAYS ACROSS IBERIA',
      dates: '01 MAY — 09 MAY',
      ariaLabel: 'Trip dates May 1 to May 9, 2025',
    },
    facts: [
      { value: '05', label: 'cities explored' },
      { value: '07', label: 'flight legs' },
      { value: '08', label: 'nights away' },
    ],
  },
  route: {
    kicker: 'THE IBERIAN ROUTE',
    title: 'Madrid, Barcelona, Andalusia, then Lisbon.',
    mapAriaLabel: 'Interactive map of the Spain and Portugal itinerary',
    center: [39.25, -4.05],
    zoom: 5,
    minZoom: 4,
    roads: [
      [
        [37.3891, -5.9845],
        [37.1773, -3.5986],
        [37.3891, -5.9845],
      ],
    ],
    flights: [
      [
        [40.4168, -3.7038],
        [41.3851, 2.1734],
      ],
      [
        [41.3851, 2.1734],
        [37.3891, -5.9845],
      ],
      [
        [37.3891, -5.9845],
        [38.7223, -9.1393],
      ],
    ],
  },
  itinerary: {
    kicker: 'DAY BY DAY',
    title: 'The Spain and Portugal itinerary.',
    days: [
      {
        id: 'may-1',
        date: 'MAY 01',
        day: 'THURSDAY',
        place: 'Beijing → Dubai → Madrid',
        weather: 'Rainy',
        temperature: '11–20°',
        coordinate: [40.4168, -3.7038],
        entries: [
          {
            type: 'flight',
            title: '07:25–11:50 · EK309',
            detail: 'Beijing Capital T3 (PEK) → Dubai T3 (DXB)',
            cost: 13338,
            costNote: 'International round-trip airfare · 2 people',
            costShared: true,
          },
          {
            type: 'flight',
            title: '14:30–20:20 · EK143',
            detail: 'Dubai T3 (DXB) → Madrid T4S (MAD)',
          },
          {
            type: 'drive',
            title: 'Taxi',
            detail: 'Airport and city rides · combined trip total',
            cost: 1574,
            costShared: true,
          },
          { type: 'food', title: 'Burger King', cost: 136 },
          {
            type: 'stay',
            title: 'Hyatt Regency Hesperia Madrid',
            cost: 5415,
            costNote: 'Night 1 of 3 · three-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'may-2',
        date: 'MAY 02',
        day: 'FRIDAY',
        place: 'Madrid museums and Retiro',
        weather: 'Rainy',
        temperature: '12–20°',
        coordinate: [40.4153, -3.6844],
        entries: [
          { type: 'visit', title: 'Gran Vía', detail: 'Madrid shopping walk' },
          {
            type: 'visit',
            title: 'Museo Nacional del Prado',
            detail: 'Timed entry at 13:15',
            cost: 250,
            costNote: '2 people',
          },
          { type: 'visit', title: 'El Retiro Park' },
          {
            type: 'visit',
            title: 'Museo Nacional Centro de Arte Reina Sofía',
            detail: 'Evening visit at 19:00',
          },
          { type: 'drive', title: 'Madrid subway', cost: 136 },
          { type: 'food', title: 'Five Guys', cost: 181 },
          { type: 'food', title: 'Tagliatella Pasta', cost: 540 },
          {
            type: 'stay',
            title: 'Hyatt Regency Hesperia Madrid',
            cost: 5415,
            costNote: 'Night 2 of 3 · three-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'may-3',
        date: 'MAY 03',
        day: 'SATURDAY',
        place: 'Royal Madrid and Bernabéu',
        weather: 'Rainy',
        temperature: '11–18°',
        coordinate: [40.4531, -3.6883],
        entries: [
          {
            type: 'visit',
            title: 'Historic Madrid walk',
            detail: 'Plaza Mayor · Puerta del Sol',
          },
          {
            type: 'visit',
            title: 'Royal Palace of Madrid',
            detail: 'Timed entry at 13:15',
            cost: 246,
            costNote: '2 people',
          },
          {
            type: 'visit',
            title: 'Tour Bernabéu',
            detail: 'Santiago Bernabéu Stadium at 16:00',
            cost: 582,
            costNote: '2 people',
          },
          { type: 'visit', title: 'El Corte Inglés', detail: 'Evening shopping stop' },
          { type: 'food', title: 'DOCE DIOSES', cost: 285 },
          {
            type: 'stay',
            title: 'Hyatt Regency Hesperia Madrid',
            cost: 5415,
            costNote: 'Night 3 of 3 · three-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'may-4',
        date: 'MAY 04',
        day: 'SUNDAY',
        place: 'Madrid → Barcelona',
        weather: 'Partly cloudy',
        temperature: '15–22°',
        coordinate: [41.3851, 2.1734],
        entries: [
          {
            type: 'flight',
            title: '11:25–12:45 · IB411',
            detail: 'Madrid T4 (MAD) → Barcelona T1 (BCN)',
            cost: 2468,
            costNote: '2 people',
          },
          {
            type: 'visit',
            title: 'Park Güell',
            detail: 'Timed entry at 16:00',
            cost: 301,
            costNote: '2 people',
          },
          {
            type: 'visit',
            title: 'Barcelona arrival walk',
            detail: 'Casa Vicens Gaudí · pass by · Barceloneta Beach',
          },
          {
            type: 'drive',
            title: 'Uber and Bolt',
            detail: 'Combined trip total',
            cost: 1740,
            costShared: true,
          },
          { type: 'food', title: 'Jon Cake', detail: 'Reserved brie cheesecake', cost: 107 },
          { type: 'food', title: 'Maymanta', cost: 609 },
          {
            type: 'stay',
            title: 'Grand Hyatt Barcelona',
            cost: 4735,
            costNote: 'Night 1 of 2 · two-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'may-5',
        date: 'MAY 05',
        day: 'MONDAY',
        place: 'Gaudí and old Barcelona',
        weather: 'Partly cloudy',
        temperature: '14–20°',
        coordinate: [41.3917, 2.1649],
        entries: [
          {
            type: 'visit',
            title: 'Casa Milà',
            detail: 'Timed entry at 11:30',
            cost: 486,
            costNote: '2 people',
          },
          {
            type: 'visit',
            title: 'Casa Batlló',
            detail: 'Timed entry at 13:30',
            cost: 687,
            costNote: '2 people',
          },
          {
            type: 'visit',
            title: 'Barcelona architecture walk',
            detail: 'Palau de la Música Catalana · Picasso Museum · pass by',
          },
          { type: 'food', title: 'Mercat de la Boqueria' },
          { type: 'food', title: 'Lena Barcelona', cost: 889 },
          { type: 'food', title: 'Tapeo', cost: 649 },
          { type: 'food', title: 'Grand Hyatt room service', cost: 510 },
          {
            type: 'stay',
            title: 'Grand Hyatt Barcelona',
            cost: 4735,
            costNote: 'Night 2 of 2 · two-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'may-6',
        date: 'MAY 06',
        day: 'TUESDAY',
        place: 'Barcelona → Seville',
        weather: 'Partly cloudy',
        temperature: '14–17°',
        coordinate: [37.3891, -5.9845],
        entries: [
          {
            type: 'visit',
            title: 'Sagrada Família',
            detail: 'Basilica at 14:30 · Passion façade tower at 15:15',
            cost: 573,
            costNote: '2 people',
          },
          { type: 'food', title: 'El Glop Gaudí', cost: 270 },
          { type: 'food', title: 'McDonald’s', cost: 244 },
          {
            type: 'flight',
            title: '21:15–22:55 · VY2220',
            detail: 'Barcelona T1 (BCN) → Seville (SVQ)',
            cost: 1484,
            costNote: '2 people',
          },
          {
            type: 'stay',
            title: 'Novotel Sevilla',
            cost: 3327,
            costNote: 'Night 1 of 2 · two-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'may-7',
        date: 'MAY 07',
        day: 'WEDNESDAY',
        place: 'Seville ↔ Granada',
        weather: 'Partly cloudy',
        temperature: '10–20°',
        coordinate: [37.1773, -3.5986],
        entries: [
          {
            type: 'drive',
            title: '09:00–12:00 · Seville → Granada',
            detail: 'Return shuttle for four passengers',
            cost: 674,
            costNote: 'Four tickets',
          },
          {
            type: 'visit',
            title: 'Alhambra',
            detail: 'Nasrid Palaces timed entry at 14:30',
            cost: 302,
            costNote: '2 people',
          },
          { type: 'visit', title: 'Mirador de San Nicolás' },
          {
            type: 'drive',
            title: '19:30–22:30 · Granada → Seville',
            detail: 'Return shuttle',
          },
          { type: 'food', title: 'El Balcón de San Nicolás', cost: 77 },
          { type: 'food', title: 'Domino’s Pizza', cost: 171 },
          {
            type: 'stay',
            title: 'Novotel Sevilla',
            cost: 3327,
            costNote: 'Night 2 of 2 · two-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'may-8',
        date: 'MAY 08',
        day: 'THURSDAY',
        place: 'Seville → Lisbon',
        weather: 'Partly cloudy',
        temperature: '13–22°',
        coordinate: [38.7223, -9.1393],
        entries: [
          {
            type: 'visit',
            title: 'Seville parks and plazas',
            detail: 'Plaza de España · Parque de María Luisa',
          },
          {
            type: 'visit',
            title: 'Royal Alcázar of Seville',
            detail: 'Timed entry at 10:30',
            cost: 259,
            costNote: '2 people',
          },
          {
            type: 'visit',
            title: 'Catedral de Sevilla',
            detail: 'Timed entry at 12:50',
            cost: 222,
            costNote: '2 people',
          },
          { type: 'food', title: 'San Marco Santa Cruz' },
          { type: 'food', title: 'SSP Spain at the airport', cost: 257 },
          { type: 'food', title: 'Ostras Sobar', cost: 90 },
          {
            type: 'flight',
            title: '16:25–16:35 · FR3629',
            detail: 'Seville (SVQ) → Lisbon T1 (LIS)',
            cost: 1682,
            costNote: '2 people',
          },
          {
            type: 'stay',
            title: 'Hyatt Regency Lisbon',
            cost: 2085,
            costNote: '1 night',
          },
        ],
      },
      {
        id: 'may-9',
        date: 'MAY 09',
        day: 'FRIDAY',
        place: 'Lisbon → Dubai → Beijing',
        weather: 'Partly cloudy',
        temperature: '13–21°',
        coordinate: [38.7223, -9.1393],
        entries: [
          {
            type: 'visit',
            title: 'Lisbon hills and Belém',
            detail: 'Tram 28 · Santa Justa Lift · Belém Tower · Pastéis de Belém',
          },
          { type: 'drive', title: 'City buses', cost: 298 },
          { type: 'food', title: 'Restaurante Recomendo', cost: 701 },
          { type: 'food', title: 'Starbucks', cost: 80 },
          {
            type: 'flight',
            title: '21:15–08:05 +1 · EK194',
            detail: 'Lisbon T1 (LIS) → Dubai T3 (DXB)',
          },
          {
            type: 'flight',
            title: '10:50–22:20 +1 · EK308',
            detail: 'Dubai T3 (DXB) → Beijing Capital T3 (PEK)',
          },
        ],
      },
    ],
  },
  costs: {
    currency: 'CNY',
    summaries: {
      all: { label: 'Trip total · 2 people · purchases excluded', total: 56923 },
      flight: { label: 'Flights total · 2 people', total: 18972 },
      drive: { label: 'Ground transport total', total: 4422 },
      food: { label: 'Dining total', total: 6258 },
      stay: { label: 'Stays total', total: 15562 },
      visit: { label: 'Activities total', total: 3908 },
    },
    other: [
      {
        filter: 'food',
        category: 'Dining',
        item: 'Fruit, snacks, and drinks',
        detail: 'Combined trip total',
        cost: 462,
      },
      { filter: 'all', category: 'Souvenirs', item: 'General souvenirs', cost: 1434 },
      { filter: 'all', category: 'Souvenirs', item: 'Real Madrid Store', cost: 1960 },
      { filter: 'all', category: 'Souvenirs', item: 'Ibérico ham', cost: 862 },
      { filter: 'all', category: 'Souvenirs', item: 'Orange Tree', cost: 451 },
      { filter: 'all', category: 'Souvenirs', item: 'Duty free', cost: 429 },
      { filter: 'all', category: 'Souvenirs', item: 'Ementa', cost: 777 },
      {
        filter: 'all',
        category: 'Travel',
        item: 'Visas',
        detail: 'CNY 879 each · 2 people',
        cost: 1758,
      },
      {
        filter: 'all',
        category: 'Travel',
        item: 'Phone cards',
        detail: 'CNY 65 each · 2 people',
        cost: 130,
      },
    ],
    note:
      'Hotels 15,562 · transport 23,394 · activities 3,908 · dining 6,258 · souvenirs 7,801',
  },
  footer: {
    mark: 'IBERIA / 25',
    note: 'Mapped from nine spring days across Spain and Portugal in 2025.',
  },
};
