import type { TravelConfig } from '../types';

export const ukIrelandTrip: TravelConfig = {
  slug: 'ukireland',
  countryName: 'United Kingdom + Ireland',
  theme: {
    ink: '#18352f',
    inkRgb: '24, 53, 47',
    cream: '#e9e2d3',
    creamRgb: '233, 226, 211',
    paper: '#fbf8f0',
    paperRgb: '251, 248, 240',
    accent: '#bd4c3c',
    accentRgb: '189, 76, 60',
    secondary: '#a9b9ae',
  },
  brand: {
    code: 'UK',
    year: '24',
  },
  home: {
    kicker: 'FIELD NOTE · SEP—OCT 2024',
    title: 'From London landmarks to Dublin streets.',
    description:
      'Nine autumn days through London, Cambridge, the Seven Sisters, Edinburgh, and Dublin—rainy capitals, university courts, and coastal cliffs.',
    actionLabel: 'Open the UK and Ireland itinerary',
  },
  hero: {
    kicker: 'UNITED KINGDOM + IRELAND · AUTUMN 2024',
    title: ['Rainy capitals,', 'coastal cliffs.'],
    intro:
      'A fast-moving autumn route from London’s royal landmarks to Cambridge colleges, the Sussex coast, Edinburgh’s hills, and one final Dublin day.',
    stamp: {
      number: '09',
      label: 'DAYS ACROSS THE ISLES',
      dates: '28 SEP — 06 OCT',
      ariaLabel: 'Trip dates September 28 to October 6, 2024',
    },
    facts: [
      { value: '04', label: 'city bases' },
      { value: '06', label: 'flight legs' },
      { value: '08', label: 'nights away' },
    ],
  },
  route: {
    kicker: 'THE UK + IRELAND ROUTE',
    title: 'London, Cambridge, the coast, Edinburgh, then Dublin.',
    mapAriaLabel: 'Interactive map of the United Kingdom and Ireland itinerary',
    center: [53.15, -2.15],
    zoom: 5,
    minZoom: 4,
    roads: [
      [
        [51.5074, -0.1278],
        [52.2053, 0.1218],
        [51.5074, -0.1278],
        [50.742, 0.174],
        [51.5053, 0.0553],
      ],
    ],
    flights: [
      [
        [51.5053, 0.0553],
        [55.9533, -3.1883],
      ],
      [
        [55.9533, -3.1883],
        [53.3498, -6.2603],
      ],
      [
        [53.3498, -6.2603],
        [51.47, -0.4543],
      ],
    ],
  },
  itinerary: {
    kicker: 'DAY BY DAY',
    title: 'The UK and Ireland itinerary.',
    days: [
      {
        id: 'sep-28',
        date: 'SEP 28',
        day: 'SATURDAY',
        place: 'Beijing → Frankfurt → London',
        coordinate: [51.5074, -0.1278],
        entries: [
          {
            type: 'flight',
            title: '13:40–18:00 · Beijing → Frankfurt',
            detail: 'Beijing Capital T3 (PEK) → Frankfurt T1 (FRA)',
            cost: 21886,
            costNote: 'International itinerary · 2 people',
            costShared: true,
          },
          {
            type: 'flight',
            title: '20:00–20:40 · Frankfurt → London',
            detail: 'Frankfurt T1 (FRA) → London Heathrow T2 (LHR)',
          },
          {
            type: 'food',
            title: 'Uber Eats',
            detail: 'Arrival-night meal',
            cost: 159,
          },
          {
            type: 'stay',
            title: 'Hyatt Regency London Albert Embankment',
            cost: 9545,
            costNote: 'Night 1 of 4 · four-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'sep-29',
        date: 'SEP 29',
        day: 'SUNDAY',
        place: 'Royal London and the Thames',
        weather: 'Rainy',
        temperature: '6–14°',
        coordinate: [51.5014, -0.1419],
        entries: [
          {
            type: 'visit',
            title: 'Buckingham Palace',
            detail: 'Changing of the Guard · Forecourt at 11:00 · palace visit at 11:30',
          },
          { type: 'visit', title: 'Hyde Park' },
          {
            type: 'visit',
            title: 'Westminster walk',
            detail: '10 Downing Street · Big Ben · London Eye',
          },
          {
            type: 'drive',
            title: 'London public transport',
            detail: 'Combined trip total',
            cost: 651,
          },
          {
            type: 'drive',
            title: 'Uber',
            detail: 'Combined trip total',
            cost: 2619,
          },
          {
            type: 'food',
            title: 'The Wilmington at King’s Cross',
            cost: 1536,
          },
          {
            type: 'food',
            title: 'Starbucks',
            detail: 'Combined trip total',
            cost: 469,
          },
          {
            type: 'stay',
            title: 'Hyatt Regency London Albert Embankment',
            cost: 9545,
            costNote: 'Night 2 of 4 · four-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'sep-30',
        date: 'SEP 30',
        day: 'MONDAY',
        place: 'Museums, the Tower, and Greenwich',
        weather: 'Rainy',
        temperature: '11–16°',
        coordinate: [51.4769, 0.0005],
        entries: [
          {
            type: 'visit',
            title: 'The British Museum',
            detail: 'Timed entry at 10:00',
          },
          {
            type: 'visit',
            title: 'St Paul’s Cathedral',
            detail: 'Optional stop',
          },
          { type: 'visit', title: 'Tower of London' },
          {
            type: 'visit',
            title: 'Greenwich Park and Royal Observatory',
            cost: 375,
            costNote: '2 people',
          },
          {
            type: 'food',
            title: 'Benugo at the British Museum',
            cost: 169,
          },
          {
            type: 'food',
            title: 'Rosa’s at Greenwich',
            cost: 781,
          },
          {
            type: 'stay',
            title: 'Hyatt Regency London Albert Embankment',
            cost: 9545,
            costNote: 'Night 3 of 4 · four-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'oct-1',
        date: 'OCT 01',
        day: 'TUESDAY',
        place: 'Galleries and London shopping',
        weather: 'Rainy',
        temperature: '9–15°',
        coordinate: [51.5074, -0.1278],
        entries: [
          { type: 'visit', title: 'The National Gallery' },
          { type: 'visit', title: 'Victoria and Albert Museum' },
          {
            type: 'visit',
            title: 'Harrods and Selfridges',
            detail: 'London shopping afternoon',
          },
          {
            type: 'food',
            title: 'Victoria and Albert Museum Café',
            cost: 353,
          },
          {
            type: 'food',
            title: 'Bone Daddies at Selfridges',
            cost: 691,
          },
          {
            type: 'stay',
            title: 'Hyatt Regency London Albert Embankment',
            cost: 9545,
            costNote: 'Night 4 of 4 · four-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'oct-2',
        date: 'OCT 02',
        day: 'WEDNESDAY',
        place: 'Westminster → Cambridge',
        weather: 'Cloudy',
        temperature: '8–15°',
        coordinate: [52.2053, 0.1218],
        entries: [
          {
            type: 'visit',
            title: 'Westminster Abbey',
            detail: 'Timed entry at 10:00',
            cost: 565,
            costNote: '2 people',
          },
          {
            type: 'drive',
            title: 'King’s Cross → Cambridge',
            detail: '11:42–12:30 or 12:12–13:00 · 4 rail tickets',
            cost: 907,
          },
          {
            type: 'drive',
            title: 'Cambridge public transport',
            cost: 102,
          },
          {
            type: 'visit',
            title: 'Cambridge university walk',
            detail: 'Bridge of Sighs · University of Cambridge · Newton’s Apple Tree · Corpus Clock',
          },
          {
            type: 'visit',
            title: 'King’s College, Cambridge',
            detail: 'Xu Zhimo Memorial Stone',
            cost: 297,
            costNote: '2 people',
          },
          {
            type: 'visit',
            title: 'Let’s Go Punting',
            cost: 281,
            costNote: '2 people',
          },
          {
            type: 'food',
            title: 'Aromi at Cambridge',
            cost: 409,
          },
          {
            type: 'food',
            title: 'Jack’s Gelato',
            cost: 81,
          },
          {
            type: 'food',
            title: 'Snacks, water, everyday items',
            detail: 'Combined trip total',
            cost: 231,
          },
          {
            type: 'stay',
            title: 'Hyatt Centric Cambridge',
            cost: 1004,
            costNote: '1 night',
          },
        ],
      },
      {
        id: 'oct-3',
        date: 'OCT 03',
        day: 'THURSDAY',
        place: 'Cambridge → Seven Sisters → London',
        weather: 'Sunny',
        temperature: '7–16°',
        coordinate: [50.742, 0.174],
        entries: [
          {
            type: 'drive',
            title: 'Cambridge → King’s Cross → Victoria',
            detail: '10:14–11:02 to King’s Cross · approximately 20 min to Victoria',
          },
          {
            type: 'drive',
            title: 'Victoria → Eastbourne',
            detail: '12:24–13:51 · four rail tickets',
            cost: 810,
          },
          {
            type: 'drive',
            title: 'Brighton and Eastbourne public transport',
            detail: 'Eastbourne Pier 14:30 → Belle Tout 14:51',
            cost: 206,
          },
          {
            type: 'visit',
            title: 'Seven Sisters and Birling Gap',
            detail: 'Birling Gap 16:55 → Eastbourne Station 17:13',
          },
          {
            type: 'drive',
            title: 'Eastbourne → London Victoria',
            detail: '17:33–19:06',
          },
          {
            type: 'food',
            title: 'McDonald’s at Eastbourne',
            cost: 107,
          },
          {
            type: 'stay',
            title: 'Courtyard London City Airport',
            cost: 1205,
            costNote: '1 night',
          },
        ],
      },
      {
        id: 'oct-4',
        date: 'OCT 04',
        day: 'FRIDAY',
        place: 'London → Edinburgh',
        weather: 'Rainy',
        temperature: '7–13°',
        coordinate: [55.9533, -3.1883],
        entries: [
          {
            type: 'flight',
            title: '11:25–12:45 · BA8704',
            detail: 'London City (LCY) → Edinburgh (EDI)',
            cost: 2945,
            costNote: '2 people',
          },
          {
            type: 'drive',
            title: 'Edinburgh public transport',
            cost: 76,
          },
          {
            type: 'visit',
            title: 'Edinburgh Castle',
            cost: 366,
            costNote: '2 people',
          },
          {
            type: 'visit',
            title: 'Edinburgh old town and hills',
            detail: 'Princes Street · Royal Mile · Greyfriars Kirkyard · Calton Hill · Arthur’s Seat',
          },
          { type: 'food', title: 'Tasty Buns', cost: 43 },
          { type: 'food', title: 'Jelato', cost: 40 },
          {
            type: 'stay',
            title: 'W Edinburgh + dinner',
            cost: 4074,
            costNote: '1 night · dinner included',
          },
        ],
      },
      {
        id: 'oct-5',
        date: 'OCT 05',
        day: 'SATURDAY',
        place: 'Edinburgh → Dublin',
        weather: 'Rainy',
        temperature: '10–14°',
        coordinate: [53.3498, -6.2603],
        entries: [
          { type: 'visit', title: 'North Bridge' },
          {
            type: 'flight',
            title: '15:15–16:35 · EL159',
            detail: 'Edinburgh (EDI) → Dublin (DUB)',
            cost: 2494,
            costNote: '2 people',
          },
          { type: 'visit', title: 'Guinness Storehouse' },
          {
            type: 'stay',
            title: 'Hyatt Centric The Liberties Dublin + dinner',
            cost: 2576,
            costNote: '1 night · dinner included',
          },
        ],
      },
      {
        id: 'oct-6',
        date: 'OCT 06',
        day: 'SUNDAY',
        place: 'Dublin → London → Beijing',
        weather: 'Rainy',
        temperature: '9–13°',
        coordinate: [53.3498, -6.2603],
        entries: [
          {
            type: 'visit',
            title: 'Dublin city walk',
            detail: 'Ha’penny Bridge · Temple Bar · The Spire · Phoenix Park · Trinity College Dublin',
          },
          {
            type: 'food',
            title: 'Arnotts at Dublin',
            cost: 78,
          },
          {
            type: 'flight',
            title: '18:00–19:25 · Dublin → London',
            detail: 'Dublin T2 (DUB) → London Heathrow T2 (LHR)',
          },
          {
            type: 'flight',
            title: '22:20–15:15 +1 · London → Beijing',
            detail: 'London Heathrow T2 (LHR) → Beijing Capital T3 (PEK)',
          },
        ],
      },
    ],
  },
  costs: {
    currency: 'CNY',
    summaries: {
      all: { label: 'Trip total · 2 people', total: 107643 },
      flight: { label: 'Flights total · 2 people', total: 27325 },
      drive: { label: 'Ground transport total', total: 5372 },
      food: { label: 'Dining total', total: 5147 },
      stay: { label: 'Stays total', total: 18404 },
      visit: { label: 'Activities total · 2 people', total: 1884 },
    },
    other: [
      { filter: 'all', category: 'Travel prep', item: 'UK visas', detail: '2 people', cost: 2210 },
      { filter: 'all', category: 'Travel prep', item: 'Visa courier service', detail: '2 people', cost: 202 },
      { filter: 'all', category: 'Travel prep', item: 'SIM cards', detail: '2 cards', cost: 158 },
      { filter: 'all', category: 'Souvenirs', item: 'The British Museum', cost: 685 },
      { filter: 'all', category: 'Souvenirs', item: 'Meridian at Greenwich', cost: 42 },
      { filter: 'all', category: 'Souvenirs', item: 'The National Gallery', cost: 114 },
      { filter: 'all', category: 'Souvenirs', item: 'Victoria and Albert Museum', cost: 57 },
      { filter: 'all', category: 'Souvenirs', item: 'Ed Sheeran vinyl', cost: 423 },
      { filter: 'all', category: 'Souvenirs', item: 'Swish Edinburgh', cost: 262 },
      { filter: 'all', category: 'Souvenirs', item: 'Johnnie Walker whisky', cost: 1409 },
      { filter: 'all', category: 'Souvenirs', item: 'Tartan Weaving Mill', cost: 739 },
      { filter: 'all', category: 'Souvenirs', item: 'The Sweater Shop', cost: 544 },
      { filter: 'all', category: 'Souvenirs', item: 'Trinity Woollen Mills', cost: 233 },
      { filter: 'all', category: 'Souvenirs', item: 'Airport biscuits and chocolate', cost: 2002 },
      { filter: 'all', category: 'Purchases', item: 'CHANEL', cost: 38586 },
      { filter: 'all', category: 'Purchases', item: 'Jellycat', cost: 1846 },
    ],
    note: 'Excluding purchases: CNY 67,211 · purchases: CNY 40,432',
  },
  footer: {
    mark: 'UK + IRELAND / 24',
    note: 'Mapped from nine autumn days across the United Kingdom and Ireland in 2024.',
  },
};
