import type { TravelConfig } from '../types';

export const usEastTrip: TravelConfig = {
  slug: 'useast',
  countryName: 'United States East Coast',
  theme: {
    ink: '#103754',
    inkRgb: '16, 55, 84',
    cream: '#eee6d8',
    creamRgb: '238, 230, 216',
    paper: '#fffaf2',
    paperRgb: '255, 250, 242',
    accent: '#b64050',
    accentRgb: '182, 64, 80',
    secondary: '#a8bdc8',
  },
  brand: {
    code: 'US',
    year: '24',
  },
  home: {
    kicker: 'FIELD NOTE · MAY 2024',
    title: 'From Miami heat to Manhattan nights.',
    description:
      'Fourteen days across the East Coast—Miami color, Orlando theme parks, Washington monuments, and a long New York finale.',
    actionLabel: 'Open the East Coast itinerary',
  },
  hero: {
    kicker: 'EAST COAST · SPRING 2024',
    title: ['Sunshine south,', 'city lights north.'],
    intro:
      'The route dropped into Miami, crossed Orlando’s parks, paused among Washington’s monuments, and finished with four days on New York streets.',
    stamp: {
      number: '14',
      label: 'DAYS ON THE EAST COAST',
      dates: '01 MAY — 14 MAY',
      ariaLabel: 'Trip dates May 1 to May 14, 2024',
    },
    facts: [
      { value: '04', label: 'major cities' },
      { value: '06', label: 'flight legs' },
      { value: '12', label: 'nights away' },
    ],
  },
  route: {
    kicker: 'THE EAST COAST ROUTE',
    title: 'Florida first, then north through the capital.',
    mapAriaLabel: 'Interactive map of the United States East Coast itinerary',
    center: [34.9, -78.2],
    zoom: 4,
    minZoom: 3,
    roads: [
      [
        [25.7617, -80.1918],
        [28.5383, -81.3792],
      ],
      [
        [38.9072, -77.0369],
        [41.3158, -74.1263],
        [40.7128, -74.006],
      ],
    ],
    flights: [
      [
        [40.7128, -74.006],
        [25.7617, -80.1918],
      ],
      [
        [28.5383, -81.3792],
        [38.9072, -77.0369],
      ],
    ],
  },
  itinerary: {
    kicker: 'DAY BY DAY',
    title: 'The East Coast itinerary.',
    days: [
      {
        id: 'may-1',
        date: 'MAY 01',
        day: 'WEDNESDAY',
        place: 'Beijing → New York',
        weather: 'Partly cloudy',
        temperature: '12–21°',
        coordinate: [40.7128, -74.006],
        entries: [
          {
            type: 'flight',
            title: '15:30–18:30 · OZ334',
            detail: 'Beijing (PEK) → Seoul Incheon (ICN)',
            cost: 23154,
            costNote: 'Round-trip international airfare · 2 people',
            costShared: true,
          },
          {
            type: 'flight',
            title: '21:30–23:00 · OZ224',
            detail: 'Seoul Incheon (ICN) → New York (JFK)',
            cost: 23154,
            costNote: 'Round-trip international airfare · 2 people',
            costShared: true,
          },
          {
            type: 'stay',
            title: 'TWA Hotel',
            cost: 2533,
            costNote: '1 night',
          },
        ],
      },
      {
        id: 'may-2',
        date: 'MAY 02',
        day: 'THURSDAY',
        place: 'New York → Miami',
        weather: 'Sunny',
        temperature: '22–29°',
        coordinate: [25.7617, -80.1918],
        entries: [
          {
            type: 'flight',
            title: '12:22–15:35 · B62593',
            detail: 'New York (JFK) → Miami (MIA)',
            cost: 2954,
            costNote: '2 people',
          },
          {
            type: 'drive',
            title: 'Avis car rental · Miami',
            detail: 'Pickup at 15:30 · two rentals combined',
            cost: 929,
            costNote: 'Combined rental total',
            costShared: true,
          },
          { type: 'visit', title: 'Miami city walk' },
          {
            type: 'food',
            title: 'Airport dining · JFK and MIA',
            cost: 1030,
            costNote: 'Combined airport total',
            costShared: true,
          },
          { type: 'food', title: 'CVICHE 105', cost: 1125 },
          {
            type: 'stay',
            title: 'Hyatt Regency Miami',
            cost: 3000,
            costNote: '2-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'may-3',
        date: 'MAY 03',
        day: 'FRIDAY',
        place: 'Miami',
        weather: 'Sunny',
        temperature: '23–29°',
        coordinate: [25.7617, -80.1918],
        entries: [
          {
            type: 'visit',
            title: 'Vizcaya Museum and Gardens',
            cost: 364,
            costNote: '2 people',
          },
          {
            type: 'visit',
            title: 'Formula 1 Miami Grand Prix',
            cost: 1723,
            costNote: '2 people',
          },
          { type: 'food', title: 'Miami and F1 casual eats', cost: 724 },
          { type: 'food', title: 'Nikki Beach', cost: 890 },
          {
            type: 'stay',
            title: 'Hyatt Regency Miami',
            cost: 3000,
            costNote: '2-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'may-4',
        date: 'MAY 04',
        day: 'SATURDAY',
        place: 'Miami → Orlando',
        weather: 'Sunny',
        temperature: '20–32°',
        coordinate: [28.5383, -81.3792],
        entries: [
          {
            type: 'drive',
            title: 'Miami → Orlando',
            detail: 'Approximately 380 km · 4 hr',
          },
          {
            type: 'drive',
            title: 'Avis car rental return',
            detail: 'Orlando · 16:00',
          },
          { type: 'food', title: 'Disney Springs casual eats', cost: 414 },
          {
            type: 'stay',
            title: 'Universal’s Endless Summer Resort · Surfside Inn',
            cost: 1632,
            costNote: '1 night',
          },
        ],
      },
      {
        id: 'may-5',
        date: 'MAY 05',
        day: 'SUNDAY',
        place: 'Universal Orlando',
        weather: 'Sunny',
        temperature: '21–32°',
        coordinate: [28.4734, -81.4692],
        entries: [
          {
            type: 'visit',
            title: 'Universal Islands of Adventure',
            detail: 'Park opening · 08:00',
            cost: 3157,
            costNote: '2-park, 1-day tickets · 2 people',
            costShared: true,
          },
          {
            type: 'visit',
            title: 'Universal Studios Florida',
            cost: 3157,
            costNote: '2-park, 1-day tickets · 2 people',
            costShared: true,
          },
          { type: 'food', title: 'Universal Orlando dining', cost: 1073 },
          { type: 'food', title: 'Sebastian’s Bistro', cost: 733 },
          {
            type: 'stay',
            title: 'Disney’s Caribbean Beach Resort',
            cost: 7314,
            costNote: '3-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'may-6',
        date: 'MAY 06',
        day: 'MONDAY',
        place: 'Magic Kingdom',
        weather: 'Sunny',
        temperature: '21–32°',
        coordinate: [28.4177, -81.5812],
        entries: [
          {
            type: 'visit',
            title: 'Magic Kingdom',
            cost: 7921,
            costNote: '3-day Park Hopper tickets · 2 people',
            costShared: true,
          },
          {
            type: 'visit',
            title: 'Disney Genie+ and Lightning Lane',
            cost: 2066,
            costNote: 'Combined trip total',
            costShared: true,
          },
          { type: 'food', title: 'Jungle Navigation Co. Skipper Canteen', cost: 795 },
          { type: 'food', title: 'Disney casual eats', cost: 797 },
          {
            type: 'stay',
            title: 'Disney’s Caribbean Beach Resort',
            cost: 7314,
            costNote: '3-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'may-7',
        date: 'MAY 07',
        day: 'TUESDAY',
        place: 'Animal Kingdom → EPCOT',
        weather: 'Sunny',
        temperature: '20–33°',
        coordinate: [28.3553, -81.5901],
        entries: [
          {
            type: 'visit',
            title: 'Disney’s Animal Kingdom',
            cost: 7921,
            costNote: '3-day Park Hopper tickets · 2 people',
            costShared: true,
          },
          { type: 'visit', title: 'EPCOT' },
          { type: 'food', title: 'Tusker House Restaurant', cost: 1121 },
          { type: 'food', title: 'Shiki-Sai · Sushi Izakaya', cost: 1123 },
          { type: 'food', title: 'La Crêperie de Paris', cost: 406 },
          {
            type: 'stay',
            title: 'Disney’s Caribbean Beach Resort',
            cost: 7314,
            costNote: '3-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'may-8',
        date: 'MAY 08',
        day: 'WEDNESDAY',
        place: 'Hollywood Studios → EPCOT',
        weather: 'Sunny',
        temperature: '21–35°',
        coordinate: [28.3575, -81.5583],
        entries: [
          {
            type: 'visit',
            title: 'Disney’s Hollywood Studios',
            cost: 7921,
            costNote: '3-day Park Hopper tickets · 2 people',
            costShared: true,
          },
          { type: 'visit', title: 'EPCOT' },
          { type: 'food', title: 'Sci-Fi Dine-In Theater', cost: 1080 },
          { type: 'food', title: 'Babbi Babbi · Uber Eats', cost: 655 },
          {
            type: 'stay',
            title: 'Hyatt Regency Orlando International Airport',
            cost: 1428,
            costNote: '1 night',
          },
        ],
      },
      {
        id: 'may-9',
        date: 'MAY 09',
        day: 'THURSDAY',
        place: 'Orlando → Washington, D.C.',
        weather: 'Sunny',
        temperature: '13–26°',
        coordinate: [38.9072, -77.0369],
        entries: [
          {
            type: 'flight',
            title: '10:00–12:15 · B62324',
            detail: 'Orlando (MCO) → Washington Reagan (DCA)',
            cost: 2154,
            costNote: '2 people',
          },
          {
            type: 'drive',
            title: 'Avis car rental · Washington',
            detail: 'Pickup at 12:30',
          },
          { type: 'visit', title: 'National Mall' },
          { type: 'visit', title: 'Lincoln Memorial' },
          { type: 'visit', title: 'The White House' },
          { type: 'visit', title: 'United States Capitol' },
          { type: 'food', title: 'Baan Siam', cost: 1036 },
          { type: 'food', title: 'Washington casual eats', cost: 441 },
          {
            type: 'stay',
            title: 'Thompson Washington D.C.',
            cost: 2618,
            costNote: '1 night',
          },
        ],
      },
      {
        id: 'may-10',
        date: 'MAY 10',
        day: 'FRIDAY',
        place: 'Washington → Woodbury → New York',
        weather: 'Partly cloudy',
        temperature: '12–21°',
        coordinate: [41.3158, -74.1263],
        entries: [
          {
            type: 'drive',
            title: 'Washington, D.C. → Woodbury Common',
            detail: 'Approximately 425 km · 4 hr',
          },
          { type: 'visit', title: 'Woodbury Common Premium Outlets' },
          { type: 'food', title: 'Bonkers Chinese Burger', cost: 493 },
          {
            type: 'stay',
            title: 'Dream Downtown',
            cost: 5689,
            costNote: '3-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'may-11',
        date: 'MAY 11',
        day: 'SATURDAY',
        place: 'New York City',
        weather: 'Partly cloudy',
        temperature: '14–23°',
        coordinate: [40.7128, -74.006],
        entries: [
          {
            type: 'drive',
            title: 'Avis car rental return',
            detail: 'New York · 13:00',
          },
          { type: 'visit', title: 'New York city walk' },
          {
            type: 'visit',
            title: 'New York CityPASS',
            cost: 900,
            costNote: '2 people',
          },
          { type: 'food', title: 'Congee Village · Flushing', cost: 767 },
          {
            type: 'stay',
            title: 'Dream Downtown',
            cost: 5689,
            costNote: '3-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'may-12',
        date: 'MAY 12',
        day: 'SUNDAY',
        place: 'New York City',
        weather: 'Partly cloudy',
        temperature: '14–22°',
        coordinate: [40.7794, -73.9632],
        entries: [
          { type: 'visit', title: 'New York city walk' },
          { type: 'visit', title: 'The Metropolitan Museum of Art' },
          {
            type: 'visit',
            title: 'Hamilton',
            detail: 'Broadway performance',
            cost: 2805,
            costNote: '2 people',
          },
          { type: 'food', title: 'The Met Dining', cost: 396 },
          {
            type: 'stay',
            title: 'Dream Downtown',
            cost: 5689,
            costNote: '3-night total',
            costShared: true,
          },
        ],
      },
      {
        id: 'may-13',
        date: 'MAY 13',
        day: 'MONDAY',
        place: 'New York City',
        weather: 'Rainy',
        temperature: '13–22°',
        coordinate: [40.7614, -73.9776],
        entries: [
          { type: 'visit', title: 'New York city walk' },
          { type: 'visit', title: 'Museum of Modern Art' },
          { type: 'visit', title: 'One World Observatory' },
          { type: 'food', title: 'New York casual eats', cost: 424 },
          { type: 'food', title: 'MoMA Café', cost: 345 },
          { type: 'food', title: 'One World Observatory dining', cost: 1877 },
        ],
      },
      {
        id: 'may-14',
        date: 'MAY 14',
        day: 'TUESDAY',
        place: 'New York → Beijing',
        coordinate: [40.7128, -74.006],
        entries: [
          {
            type: 'flight',
            title: '00:35–05:10 +1 · OZ223',
            detail: 'New York (JFK) → Seoul Incheon (ICN)',
            cost: 23154,
            costNote: 'Round-trip international airfare · 2 people',
            costShared: true,
          },
          {
            type: 'flight',
            title: '08:20–09:40 · OZ331',
            detail: 'Seoul Incheon (ICN) → Beijing (PEK)',
            cost: 23154,
            costNote: 'Round-trip international airfare · 2 people',
            costShared: true,
          },
        ],
      },
    ],
  },
  costs: {
    currency: 'CNY',
    summaries: {
      all: { label: 'Trip total · 2 people', total: 99812 },
      flight: { label: 'Flights total · 2 people', total: 28262 },
      drive: { label: 'Ground transport total · 2 people', total: 6815 },
      food: { label: 'Dining total · 2 people', total: 17745 },
      stay: { label: 'Stays total · 2 people', total: 24214 },
      visit: { label: 'Activities total · 2 people', total: 18936 },
    },
    other: [
      { filter: 'drive', category: 'Transport', item: 'Fuel refills', cost: 284 },
      { filter: 'drive', category: 'Transport', item: 'Parking', cost: 87 },
      { filter: 'drive', category: 'Transport', item: 'Uber', cost: 2240 },
      { filter: 'drive', category: 'Transport', item: 'Subway', detail: '18 rides', cost: 378 },
      { filter: 'drive', category: 'Transport', item: 'Scooter and e-bike', detail: '2 rentals', cost: 248 },
      { filter: 'drive', category: 'Transport', item: 'Railway', detail: '2 people', cost: 2649 },
      { filter: 'all', category: 'Souvenirs', item: 'General souvenirs', detail: 'Combined trip total', cost: 3840 },
    ],
  },
  footer: {
    mark: 'US EAST / 24',
    note: 'Mapped from fourteen spring days across the United States East Coast.',
  },
};
