import type { TravelConfig } from '../types';

export const usWestTrip: TravelConfig = {
  slug: 'uswest',
  countryName: 'United States West Coast and Canada',
  theme: {
    ink: '#14213d',
    inkRgb: '20, 33, 61',
    cream: '#f2e8dc',
    creamRgb: '242, 232, 220',
    paper: '#fffaf3',
    paperRgb: '255, 250, 243',
    accent: '#c8323e',
    accentRgb: '200, 50, 62',
    secondary: '#a9b9c9',
  },
  brand: {
    code: 'NA',
    year: '23',
  },
  home: {
    kicker: 'FIELD NOTE · SEP—OCT 2023',
    title: 'From California sunshine to Vancouver rain.',
    description:
      'Twelve days up the Pacific edge—theme parks, Yosemite granite, San Francisco streets, Seattle landmarks, and a rain-washed finale in Vancouver.',
    actionLabel: 'Open the Pacific itinerary',
  },
  hero: {
    kicker: 'PACIFIC COAST · AUTUMN 2023',
    title: ['One coast,', 'two countries.'],
    intro:
      'California began in bright theme-park color, Yosemite changed the scale, and the journey kept moving north through San Francisco and Seattle to a rain-polished Vancouver.',
    stamp: {
      number: '12',
      label: 'DAYS UP THE COAST',
      dates: '23 SEP — 04 OCT',
      ariaLabel: 'Trip dates September 23 to October 4, 2023',
    },
    facts: [
      { value: '02', label: 'countries' },
      { value: '06', label: 'flight legs' },
      { value: '11', label: 'nights away' },
    ],
  },
  route: {
    kicker: 'THE PACIFIC ROUTE',
    title: 'California sun, then north to the rain.',
    mapAriaLabel: 'Interactive map of the United States West Coast and Canada itinerary',
    center: [41.4, -121.4],
    zoom: 4,
    minZoom: 3,
    roads: [
      [
        [34.0522, -118.2437],
        [33.8366, -117.9143],
        [34.0928, -118.3287],
        [35.7688, -119.2471],
        [37.8651, -119.5383],
        [37.7749, -122.4194],
        [36.6002, -121.8947],
        [37.3346, -122.009],
        [37.3382, -121.8863],
      ],
    ],
    flights: [
      [
        [37.3382, -121.8863],
        [47.6062, -122.3321],
      ],
      [
        [47.6062, -122.3321],
        [49.2827, -123.1207],
      ],
    ],
  },
  itinerary: {
    kicker: 'DAY BY DAY',
    title: 'The Pacific itinerary.',
    days: [
      {
        id: 'sep-23',
        date: 'SEP 23',
        day: 'SATURDAY',
        place: 'Beijing → Los Angeles',
        weather: 'Sunny',
        temperature: '15–25°',
        coordinate: [34.0522, -118.2437],
        entries: [
          {
            type: 'flight',
            title: '16:45–20:35 · CX331',
            detail: 'Beijing (PEK) → Hong Kong (HKG)',
            cost: 26278,
            costNote: 'International airfare · 2 people',
            costShared: true,
          },
          {
            type: 'flight',
            title: '00:05–22:15 · CX880',
            detail: 'Hong Kong (HKG) → Los Angeles (LAX)',
            cost: 26278,
            costNote: 'International airfare · 2 people',
            costShared: true,
          },
          {
            type: 'stay',
            title: 'Hyatt House LAX / Century Blvd',
            cost: 1447,
            costNote: 'USD 185 · 1 night',
          },
        ],
      },
      {
        id: 'sep-24',
        date: 'SEP 24',
        day: 'SUNDAY',
        place: 'Santa Monica → Anaheim',
        weather: 'Partly cloudy',
        temperature: '15–27°',
        coordinate: [33.8366, -117.9143],
        entries: [
          {
            type: 'drive',
            title: 'LAX → Santa Monica → Anaheim',
            detail: 'Approximately 90 km · coastal Los Angeles to Orange County',
          },
          { type: 'visit', title: 'Santa Monica Pier' },
          { type: 'visit', title: 'The Getty' },
          { type: 'visit', title: 'LACMA' },
          { type: 'food', title: 'Bubba Gump', cost: 1172 },
          {
            type: 'stay',
            title: 'Hilton Anaheim',
            cost: 5144,
            costNote: 'USD 199/night · 3-night total with parking',
            costShared: true,
          },
        ],
      },
      {
        id: 'sep-25',
        date: 'SEP 25',
        day: 'MONDAY',
        place: 'Disney California Adventure',
        weather: 'Sunny',
        temperature: '15–28°',
        coordinate: [33.8121, -117.919],
        entries: [
          {
            type: 'visit',
            title: 'Disney California Adventure Park',
            cost: 3660,
            costNote: 'Disneyland + Genie+ · 2 parks · 2 people',
            costShared: true,
          },
          {
            type: 'food',
            title: 'Disneyland dining',
            cost: 2227,
            costNote: 'Shared across both Disney days',
            costShared: true,
          },
          {
            type: 'stay',
            title: 'Hilton Anaheim',
            cost: 5144,
            costNote: '3-night total with parking',
            costShared: true,
          },
        ],
      },
      {
        id: 'sep-26',
        date: 'SEP 26',
        day: 'TUESDAY',
        place: 'Disneyland Park',
        weather: 'Sunny',
        temperature: '15–29°',
        coordinate: [33.8121, -117.919],
        entries: [
          {
            type: 'visit',
            title: 'Disneyland Park',
            cost: 3660,
            costNote: 'Disneyland + Genie+ · 2 parks · 2 people',
            costShared: true,
          },
          {
            type: 'food',
            title: 'Disneyland dining',
            cost: 2227,
            costNote: 'Shared across both Disney days',
            costShared: true,
          },
          {
            type: 'stay',
            title: 'Hilton Anaheim',
            cost: 5144,
            costNote: '3-night total with parking',
            costShared: true,
          },
        ],
      },
      {
        id: 'sep-27',
        date: 'SEP 27',
        day: 'WEDNESDAY',
        place: 'Anaheim → Hollywood',
        weather: 'Sunny',
        temperature: '18–30°',
        coordinate: [34.0928, -118.3287],
        entries: [
          {
            type: 'drive',
            title: 'Anaheim → Los Angeles',
            detail: 'Approximately 55 km · Orange County to Hollywood',
          },
          { type: 'visit', title: 'Citadel Outlets' },
          { type: 'visit', title: 'Hollywood Walk of Fame' },
          { type: 'visit', title: 'Griffith Observatory' },
          { type: 'food', title: 'Outlets dining', cost: 627 },
          { type: 'food', title: 'In-N-Out', cost: 89 },
          { type: 'food', title: 'Dream Hotel croissant', cost: 66 },
          {
            type: 'stay',
            title: 'Dream Hollywood',
            cost: 2338,
            costNote: 'USD 259 · 1 night with parking',
          },
        ],
      },
      {
        id: 'sep-28',
        date: 'SEP 28',
        day: 'THURSDAY',
        place: 'Hollywood → Delano',
        weather: 'Partly cloudy',
        temperature: '17–27°',
        coordinate: [35.7688, -119.2471],
        entries: [
          {
            type: 'visit',
            title: 'Universal Studios Hollywood',
            cost: 1390,
            costNote: '2 people',
          },
          { type: 'food', title: 'Universal Studios dining', cost: 742 },
          {
            type: 'drive',
            title: 'Hollywood → Delano',
            detail: 'Approximately 220 km · 2 hr 30 min',
          },
          {
            type: 'stay',
            title: 'Hyatt Place Delano',
            cost: 1063,
            costNote: 'USD 140 · budgeted under Bakersfield',
          },
        ],
      },
      {
        id: 'sep-29',
        date: 'SEP 29',
        day: 'FRIDAY',
        place: 'Delano → Yosemite',
        weather: 'Sunny',
        temperature: '3–13°',
        coordinate: [37.8651, -119.5383],
        entries: [
          {
            type: 'drive',
            title: 'Delano → Yosemite Valley',
            detail: 'Approximately 250 km · 3 hr 15 min',
          },
          { type: 'visit', title: 'Yosemite National Park' },
          { type: 'food', title: 'Yosemite dining', cost: 237 },
          {
            type: 'stay',
            title: 'Yosemite Curry Village',
            cost: 1745,
            costNote: 'USD 208 · 1 night with parking',
          },
        ],
      },
      {
        id: 'sep-30',
        date: 'SEP 30',
        day: 'SATURDAY',
        place: 'Yosemite → San Francisco',
        weather: 'Partly cloudy',
        temperature: '12–19°',
        coordinate: [37.7749, -122.4194],
        entries: [
          {
            type: 'drive',
            title: 'Yosemite → San Francisco',
            detail: 'Approximately 270 km · 3 hr 30 min',
          },
          { type: 'visit', title: 'San Francisco' },
          {
            type: 'stay',
            title: 'Hyatt House Belmont',
            cost: 1331,
            costNote: 'USD 184 · 1 night with parking',
          },
        ],
      },
      {
        id: 'oct-1',
        date: 'OCT 01',
        day: 'SUNDAY',
        place: 'Monterey → Silicon Valley',
        weather: 'Partly cloudy',
        temperature: '10–30°',
        coordinate: [37.3382, -121.8863],
        entries: [
          {
            type: 'drive',
            title: 'Belmont → Monterey → Cupertino → San Jose',
            detail: 'Approximately 210 km · Pacific coast and Silicon Valley',
          },
          { type: 'visit', title: 'Monterey' },
          { type: 'visit', title: 'Apple Park Visitor Center' },
          { type: 'food', title: 'Apple Park coffee', cost: 117 },
          { type: 'food', title: 'J Pot', cost: 542 },
          { type: 'food', title: 'San Jose Thai food', cost: 1083 },
          {
            type: 'stay',
            title: 'Hotel De Anza',
            cost: 1525,
            costNote: 'USD 208 · 1 night',
          },
        ],
      },
      {
        id: 'oct-2',
        date: 'OCT 02',
        day: 'MONDAY',
        place: 'San Jose → Seattle',
        weather: 'Partly cloudy',
        temperature: '7–21°',
        coordinate: [47.6062, -122.3321],
        entries: [
          {
            type: 'flight',
            title: '10:30–12:58 · DL3736',
            detail: 'San Jose (SJC) → Seattle (SEA)',
            cost: 2758,
            costNote: '2 people',
          },
          { type: 'visit', title: 'Space Needle' },
          { type: 'visit', title: 'Pike Place Market / Original Starbucks' },
          { type: 'food', title: 'Starbucks', cost: 327 },
          { type: 'food', title: 'Seattle Airport Qdoba', cost: 197 },
          {
            type: 'stay',
            title: 'Hyatt at Olive 8',
            cost: 2030,
            costNote: 'USD 344 · 1 night',
          },
        ],
      },
      {
        id: 'oct-3',
        date: 'OCT 03',
        day: 'TUESDAY',
        place: 'Seattle → Vancouver',
        weather: 'Rainy',
        temperature: '8–22°',
        coordinate: [49.2827, -123.1207],
        entries: [
          { type: 'visit', title: 'Microsoft Corporation · Redmond' },
          { type: 'food', title: 'Microsoft In.gredients', cost: 400 },
          {
            type: 'flight',
            title: '15:00–16:01 · AC8807',
            detail: 'Seattle (SEA) → Vancouver (YVR)',
            cost: 2852,
            costNote: '2 people',
          },
          { type: 'food', title: 'The Dolar Shop', cost: 1000 },
          {
            type: 'stay',
            title: 'JW Marriott Parq Vancouver',
            cost: 2326,
            costNote: 'CAD 433 · 1 night',
          },
        ],
      },
      {
        id: 'oct-4',
        date: 'OCT 04',
        day: 'WEDNESDAY',
        place: 'Vancouver → Beijing',
        weather: 'Rainy',
        temperature: '12–18°',
        coordinate: [49.2827, -123.1207],
        entries: [
          { type: 'visit', title: 'Gastown Steam Clock' },
          { type: 'visit', title: 'Canada Place' },
          { type: 'visit', title: 'Stanley Park' },
          { type: 'visit', title: 'Granville Island Public Market / The Lobster Man' },
          { type: 'food', title: 'Vancouver Thai', cost: 498 },
          { type: 'food', title: 'Café Medina', cost: 473 },
          { type: 'food', title: 'Flying Pan', cost: 404 },
          { type: 'food', title: 'Kin’s Farm fruit', cost: 8 },
          { type: 'food', title: 'Hong Kong dining', cost: 107 },
          {
            type: 'flight',
            title: '00:55–05:35 +1 · CX865',
            detail: 'Vancouver (YVR) → Hong Kong (HKG)',
            cost: 26278,
            costNote: 'International airfare · 2 people',
            costShared: true,
          },
          {
            type: 'flight',
            title: '12:00–15:30 +2 · CX332',
            detail: 'Hong Kong (HKG) → Beijing (PEK)',
            cost: 26278,
            costNote: 'International airfare · 2 people',
            costShared: true,
          },
        ],
      },
    ],
  },
  costs: {
    currency: 'CNY',
    summaries: {
      all: { label: 'Trip total · 2 people', total: 74797 },
      flight: { label: 'Flights total · 2 people', total: 32547 },
      drive: { label: 'Ground transport total · 2 people', total: 6343 },
      food: { label: 'Dining total · 2 people', total: 10902 },
      stay: { label: 'Stays total · 2 people', total: 18950 },
      visit: { label: 'Activities total · 2 people', total: 5050 },
    },
    other: [
      { filter: 'flight', category: 'Transport', item: 'Baggage fees', detail: '3 bags', cost: 659 },
      { filter: 'drive', category: 'Transport', item: 'Car rental', detail: '7 days', cost: 1945 },
      { filter: 'drive', category: 'Transport', item: 'Fuel refills', cost: 882 },
      { filter: 'drive', category: 'Transport', item: 'Parking', cost: 359 },
      { filter: 'drive', category: 'Transport', item: 'Uber', cost: 2962 },
      { filter: 'drive', category: 'Transport', item: 'Subway', cost: 34 },
      { filter: 'drive', category: 'Transport', item: 'Bike rental', cost: 161 },
      { filter: 'food', category: 'Dining', item: 'Uber Eats', cost: 224 },
      { filter: 'food', category: 'Dining', item: '7-Eleven Anaheim', cost: 100 },
      { filter: 'food', category: 'Dining', item: 'Supermarket', cost: 262 },
      { filter: 'all', category: 'Souvenirs', item: 'General souvenirs', detail: 'Combined trip total', cost: 1004 },
    ],
  },
  footer: {
    mark: 'US + CA / 23',
    note: 'Mapped from twelve days up the Pacific coast in autumn 2023.',
  },
};
